#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSAccountSignatureProviderOption.h"
#import "DSSignatureProviderRequiredOption.h"


@protocol DSAccountSignatureProvider
@end

@interface DSAccountSignatureProvider : DSObject

/*  [optional]
 */
@property(nonatomic) NSString* isRequired;
/*  [optional]
 */
@property(nonatomic) NSString* priority;
/*  [optional]
 */
@property(nonatomic) NSString* signatureProviderDisplayName;
/*  [optional]
 */
@property(nonatomic) NSString* signatureProviderId;
/*  [optional]
 */
@property(nonatomic) NSString* signatureProviderName;
/*  [optional]
 */
@property(nonatomic) NSArray<DSAccountSignatureProviderOption>* signatureProviderOptionsMetadata;
/*  [optional]
 */
@property(nonatomic) NSArray<DSSignatureProviderRequiredOption>* signatureProviderRequiredOptions;

@end
