#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSBillingDiscount.h"
#import "DSBillingPrice.h"


@protocol DSBillingCharge
@end

@interface DSBillingCharge : DSObject

/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* allowedQuantity;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* blocked;
/* Provides information on what services the charge item is for.  The following table provides a description of the different chargeName values available at this time.  | chargeName | Description | | --- | --- | | id_check | ID Check Charge | | in_person_signing | In Person Signing charge | | envelopes Included | Sent Envelopes for the account | | age_verify | Age verification check | | ofac | OFAC Check | | id_confirm | ID confirmation check | | student_authentication | STAN PIN authentication check | | wet_sign_fax | Pages for returning signed documents by fax | | attachment_fax | Pages for returning attachments by fax | | phone_authentication | Phone authentication charge | | powerforms | PowerForm envelopes sent | | signer_payments | Payment processing charge | | outbound_fax | Send by fax charge | | bulk_recipient_envelopes | Bulk Recipient Envelopes sent | | sms_authentications | SMS authentication charge | | saml_authentications | SAML authentication charge | | express_signer_certificate | DocuSign Express Certificate charge | | personal_signer_certificate | Personal Signer Certificate charge | | safe_certificate | SAFE BioPharma Signer Certificate charge | | seats | Included active seats charge | | open_trust_certificate | OpenTrust Signer Certificate charge | [optional]
 */
@property(nonatomic) NSString* chargeName;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* chargeType;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* chargeUnitOfMeasure;
/*  [optional]
 */
@property(nonatomic) NSArray<DSBillingDiscount>* discounts;
/*  [optional]
 */
@property(nonatomic) NSString* firstEffectiveDate;
/*  [optional]
 */
@property(nonatomic) NSString* includedQuantity;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* incrementalQuantity;
/*  [optional]
 */
@property(nonatomic) NSString* lastEffectiveDate;
/*  [optional]
 */
@property(nonatomic) NSArray<DSBillingPrice>* prices;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* unitPrice;
/*  [optional]
 */
@property(nonatomic) NSString* usedQuantity;

@end
