#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSBulkRecipientSignatureProvider.h"
#import "DSBulkRecipientTabLabel.h"
#import "DSErrorDetails.h"


@protocol DSBulkRecipient
@end

@interface DSBulkRecipient : DSObject

/* If a value is provided, the recipient must enter the value as the access code to view and sign the envelope.   Maximum Length: 50 characters and it must conform to the account’s access code format setting.  If blank, but the signer `accessCode` property is set in the envelope, then that value is used.  If blank and the signer `accessCode` property is not set, then the access code is not required. [optional]
 */
@property(nonatomic) NSString* accessCode;
/* Specifies the recipient's email address.   Maximum length: 100 characters. [optional]
 */
@property(nonatomic) NSString* email;
/* Array or errors. [optional]
 */
@property(nonatomic) NSArray<DSErrorDetails>* errorDetails;
/* Specifies the authentication check used for the signer. If blank then no authentication check is required for the signer. Only one value can be used in this field.  The acceptable values are:  * KBA: Enables the normal ID check authentication set up for your account. * Phone: Enables phone authentication. * SMS: Enables SMS authentication. [optional]
 */
@property(nonatomic) NSString* identification;
/* Specifies the recipient's name.   Maximum length: 50 characters. [optional]
 */
@property(nonatomic) NSString* name;
/* Specifies a note that is unique to this recipient. This note is sent to the recipient via the signing email. The note displays in the signing UI near the upper left corner of the document on the signing screen.  Maximum Length: 1000 characters. [optional]
 */
@property(nonatomic) NSString* note;
/* This is only used if the Identification field value is Phone or SMS. The value for this field can be a valid telephone number or, if Phone, usersupplied (SMS authentication cannot use a user supplied number). Parenthesis and dashes can be used in the telephone number.  If `usersupplied` is used, the signer supplies his or her own telephone number. [optional]
 */
@property(nonatomic) NSString* phoneNumber;
/*  [optional]
 */
@property(nonatomic) NSArray<DSBulkRecipientSignatureProvider>* recipientSignatureProviderInfo;
/*  [optional]
 */
@property(nonatomic) NSString* rowNumber;
/* Specifies values used to populate recipient tabs with information. This allows each bulk recipient signer to have different values for their associated tabs. Any number of `tabLabel` columns can be added to the bulk recipient file.  The information used in the bulk recipient file header must be the same as the `tabLabel` for the tab.  The values entered in this column are automatically inserted into the corresponding tab for the recipient in the same row.  Note that this option cannot be used for tabs that do not have data or that are automatically populated data such as Signature, Full Name, Email Address, Company, Title, and Date Signed tabs. [optional]
 */
@property(nonatomic) NSArray<DSBulkRecipientTabLabel>* tabLabels;

@end
