#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSDocument.h"
#import "DSInlineTemplate.h"
#import "DSServerTemplate.h"


@protocol DSCompositeTemplate
@end

@interface DSCompositeTemplate : DSObject

/* The identify of this composite template. It is used as a reference when adding document object information. If used, the document’s `content-disposition` must include the composite template ID to which the document should be added. If a composite template ID is not specified in the content-disposition, the document is applied based on the value of the `documentId` property only. If no document object is specified, the composite template inherits the first document. [optional]
 */
@property(nonatomic) NSString* compositeTemplateId;

@property(nonatomic) DSDocument* document;
/*  Zero or more inline templates and their position in the overlay. If supplied, they are overlaid into the envelope in the order of their Sequence value. [optional]
 */
@property(nonatomic) NSArray<DSInlineTemplate>* inlineTemplates;
/*  [optional]
 */
@property(nonatomic) NSString* pdfMetaDataTemplateSequence;
/* 0 or more server-side templates and their position in the overlay. If supplied, they are overlaid into the envelope in the order of their Sequence value [optional]
 */
@property(nonatomic) NSArray<DSServerTemplate>* serverTemplates;

@end
