#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSConnectDebugLog.h"


@protocol DSConnectLog
@end

@interface DSConnectLog : DSObject

/* The account ID associated with the envelope. [optional]
 */
@property(nonatomic) NSString* accountId;
/* The web address of the listener or Retrieving Service end point for Connect. [optional]
 */
@property(nonatomic) NSString* configUrl;
/* A complex element containing information about the Connect configuration, error details, date/time, description and payload.  This is only included in the response if the query additional_info=true is used. [optional]
 */
@property(nonatomic) NSArray<DSConnectDebugLog>* connectDebugLog;
/* The identifier for the Connect configuration that failed. If an account has multiple Connect configurations, this value is used to look up the Connect configuration for the failed post. [optional]
 */
@property(nonatomic) NSString* connectId;
/* The date and time the entry was created. [optional]
 */
@property(nonatomic) NSString* created;
/* The email that sent the envelope. [optional]
 */
@property(nonatomic) NSString* email;
/* The envelope ID of the envelope status that failed to post. [optional]
 */
@property(nonatomic) NSString* envelopeId;
/* The error that caused the Connect post to fail. [optional]
 */
@property(nonatomic) NSString* error;
/* The failure log ID for the failure. [optional]
 */
@property(nonatomic) NSString* failureId;
/* The URI for the failure. [optional]
 */
@property(nonatomic) NSString* failureUri;
/* The date and time the last attempt to post. [optional]
 */
@property(nonatomic) NSString* lastTry;
/* The Connect log ID for the entry. [optional]
 */
@property(nonatomic) NSString* logId;
/* The URI for the log item. [optional]
 */
@property(nonatomic) NSString* logUri;
/* The number of times the Connect post has been retried. [optional]
 */
@property(nonatomic) NSString* retryCount;
/* The UEI to retry to publish the Connect failure. [optional]
 */
@property(nonatomic) NSString* retryUri;
/* The new envelope status for the failed Connect post. The possible values are: Any, Voided, Created, Deleted, Sent, Delivered, Signed, Completed, Declined, TimedOut, Template, or Processing. [optional]
 */
@property(nonatomic) NSString* status;
/* The envelope subject. [optional]
 */
@property(nonatomic) NSString* subject;
/* The name of the envelope sender. [optional]
 */
@property(nonatomic) NSString* userName;

@end
