#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSErrorDetails.h"


@protocol DSCustomFieldV2
@end

@interface DSCustomFieldV2 : DSObject

/* If merge field's are being used, specifies the type of the merge field. The only  supported value is **salesforce**. [optional]
 */
@property(nonatomic) NSString* configurationType;

@property(nonatomic) DSErrorDetails* errorDetails;
/*  [optional]
 */
@property(nonatomic) NSString* fieldId;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/* When set to **true**, the signer is required to fill out this tab [optional]
 */
@property(nonatomic) NSString* required;
/*  [optional]
 */
@property(nonatomic) NSString* show;
/* The value of the custom field. [optional]
 */
@property(nonatomic) NSString* value;

@end
