#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol DSCurrencyFeatureSetPrice
@end

@interface DSCurrencyFeatureSetPrice : DSObject

/* Specifies the alternate ISO currency code for the account.  [optional]
 */
@property(nonatomic) NSString* currencyCode;
/* Specifies the alternate currency symbol for the account. [optional]
 */
@property(nonatomic) NSString* currencySymbol;
/* An incremental envelope cost for plans with envelope overages (when `isEnabled` is set to **true**.) [optional]
 */
@property(nonatomic) NSString* envelopeFee;
/* Specifies a one-time fee associated with the plan (when `isEnabled` is set to **true**.) [optional]
 */
@property(nonatomic) NSString* fixedFee;
/* Specifies an incremental seat cost for seat-based plans (when `isEnabled` is set to **true**.) [optional]
 */
@property(nonatomic) NSString* seatFee;

@end
