#import <Foundation/Foundation.h>
#import "DSErrorDetails.h"
#import "DSTabMetadata.h"
#import "DSTabMetadataList.h"
#import "DSApi.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/








@interface DSCustomTabsApi_ListOptions : DSObject
/*
 * customTabOnly When set to **true**, only custom tabs are returned in the response. 
 */
@property NSString* customTabOnly;

@end



@interface DSCustomTabsApi: NSObject <DSApi>

extern NSString* kDSCustomTabsApiErrorDomain;
extern NSInteger kDSCustomTabsApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Creates a custom tab.
/// Creates a tab with pre-defined properties, such as a text tab with a certain font type and validation pattern. Users can access the custom tabs when sending documents through the DocuSign web application.  Custom tabs can be created for approve, checkbox, company, date, date signed, decline, email, email address, envelope ID, first name, formula, full name, initial here, last name, list, note, number, radio, sign here, signer attachment, SSN, text, title, and zip tabs.
///
/// @param accountId The external account number (int) or account ID Guid.
/// @param tabMetadata  (optional)

///  code:201 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSTabMetadata*
-(NSNumber*) createWithAccountId:
(NSString*) accountId 
 tabMetadata:(DSTabMetadata*) tabMetadata

 completionHandler: (void (^)(DSTabMetadata* output, NSError* error)) handler;

/// Deletes custom tab information.
/// Deletes the custom from the specified account.
///
/// @param accountId The external account number (int) or account ID Guid./// @param customTabId 


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
-(NSNumber*) deleteWithAccountId:
(NSString*) accountId  customTabId:(NSString*) customTabId 


 completionHandler: (void (^)(NSError* error)) handler;

/// Gets custom tab information.
/// Retrieves information about the requested custom tab on the specified account.
///
/// @param accountId The external account number (int) or account ID Guid./// @param customTabId 


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSTabMetadata*
-(NSNumber*) getWithAccountId:
(NSString*) accountId  customTabId:(NSString*) customTabId 


 completionHandler: (void (^)(DSTabMetadata* output, NSError* error)) handler;

/// Gets a list of all account tabs.
/// Retrieves a list of all tabs associated with the account.
///
/// @param accountId The external account number (int) or account ID Guid.

/// @param DSCustomTabsApi_ListOptions Options for modifying the behavior of the function.
///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSTabMetadataList*
-(NSNumber*) listWithAccountId:
(NSString*) accountId 

 options:(DSCustomTabsApi_ListOptions*) options
 completionHandler: (void (^)(DSTabMetadataList* output, NSError* error)) handler;

/// Updates custom tab information.  
/// Updates the information in a custom tab for the specified account.
///
/// @param accountId The external account number (int) or account ID Guid./// @param customTabId 
/// @param tabMetadata  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSTabMetadata*
-(NSNumber*) updateWithAccountId:
(NSString*) accountId  customTabId:(NSString*) customTabId 
 tabMetadata:(DSTabMetadata*) tabMetadata

 completionHandler: (void (^)(DSTabMetadata* output, NSError* error)) handler;


@end
