#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSCurrencyFeatureSetPrice.h"


@protocol DSFeatureSet
@end

@interface DSFeatureSet : DSObject

/* A complex type that contains alternate currency values that are configured for this plan feature set. [optional]
 */
@property(nonatomic) NSArray<DSCurrencyFeatureSetPrice>* currencyFeatureSetPrices;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeFee;
/* A unique ID for the feature set. [optional]
 */
@property(nonatomic) NSString* featureSetId;
/*  [optional]
 */
@property(nonatomic) NSString* fixedFee;
/* When set to **true**, indicates that this module is enabled on the account. [optional]
 */
@property(nonatomic) NSString* is21CFRPart11;
/*  [optional]
 */
@property(nonatomic) NSString* isActive;
/* Specifies whether the feature set is actively enabled as part of the plan. [optional]
 */
@property(nonatomic) NSString* isEnabled;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/* An incremental seat cost for seat-based plans. Only valid when isEnabled for the feature set is set to true. [optional]
 */
@property(nonatomic) NSString* seatFee;

@end
