#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSRecipients.h"


@protocol DSFolderItemV2
@end

@interface DSFolderItemV2 : DSObject

/* Specifies the date and time this item was completed. [optional]
 */
@property(nonatomic) NSString* completedDateTime;
/* Indicates the date and time the item was created. [optional]
 */
@property(nonatomic) NSString* createdDateTime;
/* The envelope ID of the envelope status that failed to post. [optional]
 */
@property(nonatomic) NSString* envelopeId;
/* Contains a URI for an endpoint that you can use to retrieve the envelope or envelopes. [optional]
 */
@property(nonatomic) NSString* envelopeUri;
/* The date and time the envelope is set to expire. [optional]
 */
@property(nonatomic) NSString* expireDateTime;
/*  [optional]
 */
@property(nonatomic) NSString* folderId;
/*  [optional]
 */
@property(nonatomic) NSString* folderUri;
/* When set to **true**, indicates that this module is enabled on the account. [optional]
 */
@property(nonatomic) NSString* is21CFRPart11;
/*  [optional]
 */
@property(nonatomic) NSString* isSignatureProviderEnvelope;
/* The date and time the item was last modified. [optional]
 */
@property(nonatomic) NSString* lastModifiedDateTime;
/*  [optional]
 */
@property(nonatomic) NSString* ownerName;

@property(nonatomic) DSRecipients* recipients;
/* Contains a URI for an endpoint that you can use to retrieve the recipients. [optional]
 */
@property(nonatomic) NSString* recipientsUri;
/*  [optional]
 */
@property(nonatomic) NSString* senderCompany;
/*  [optional]
 */
@property(nonatomic) NSString* senderEmail;
/*  [optional]
 */
@property(nonatomic) NSString* senderName;
/*  [optional]
 */
@property(nonatomic) NSString* senderUserId;
/* The date and time the envelope was sent. [optional]
 */
@property(nonatomic) NSString* sentDateTime;
/* Indicates the envelope status. Valid values are:  * sent - The envelope is sent to the recipients.  * created - The envelope is saved as a draft and can be modified and sent later. [optional]
 */
@property(nonatomic) NSString* status;
/*  [optional]
 */
@property(nonatomic) NSString* subject;

@end
