#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DSEnvelope.h"
#import "DSDocument.h"
#import "DSCustomFields.h"
#import "DSRecipients.h"


@protocol DSInlineTemplate
@end

@interface DSInlineTemplate : DSObject

/* Specifies the order in which templates are overlaid. [optional]
 */
@property(nonatomic) NSString* sequence;

@property(nonatomic) DSEnvelope* envelope;
/* Complex element contains the details on the documents in the envelope. [optional]
 */
@property(nonatomic) NSArray<DSDocument>* documents;

@property(nonatomic) DSRecipients* recipients;

@property(nonatomic) DSCustomFields* customFields;

@end
