#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSErrorDetails.h"
#import "DSUserInfo.h"


@protocol DSLockInformation
@end

@interface DSLockInformation : DSObject


@property(nonatomic) DSErrorDetails* errorDetails;
/* Sets the time, in seconds, until the lock expires when there is no activity on the envelope.  If no value is entered, then the default value of 300 seconds is used. The maximum value is 1,800 seconds.  The lock duration can be extended.  [optional]
 */
@property(nonatomic) NSString* lockDurationInSeconds;
/* Specifies the friendly name of  the application that is locking the envelope. [optional]
 */
@property(nonatomic) NSString* lockedByApp;

@property(nonatomic) DSUserInfo* lockedByUser;
/* The datetime until the envelope lock expires. [optional]
 */
@property(nonatomic) NSString* lockedUntilDateTime;
/* A unique identifier provided to the owner of the envelope lock.   Used to prove ownership of the lock. [optional]
 */
@property(nonatomic) NSString* lockToken;
/* The type of envelope lock.  Currently \"edit\" is the only supported type. [optional]
 */
@property(nonatomic) NSString* lockType;
/* Reserved for future use.  Indicates whether a scratchpad is used for editing information.   [optional]
 */
@property(nonatomic) NSString* useScratchPad;

@end
