#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSAccountAddress.h"
#import "DSCreditCardInformation.h"
#import "DSNameValue.h"
#import "DSPlanInformation.h"
#import "DSReferralInformation.h"
#import "DSSocialAccountInformation.h"
#import "DSUserInformation.h"


@protocol DSNewAccountDefinition
@end

@interface DSNewAccountDefinition : DSObject

/* The account name for the new account. [optional]
 */
@property(nonatomic) NSString* accountName;
/* The list of account settings. These determine the features available for the account. Note that some features are determined by the plan used to create the account, and cannot be overridden. [optional]
 */
@property(nonatomic) NSArray<DSNameValue>* accountSettings;

@property(nonatomic) DSAccountAddress* addressInformation;

@property(nonatomic) DSCreditCardInformation* creditCardInformation;
/* The code that identifies the billing plan groups and plans for the new account. [optional]
 */
@property(nonatomic) NSString* distributorCode;
/* The password for the distributorCode. [optional]
 */
@property(nonatomic) NSString* distributorPassword;

@property(nonatomic) DSUserInformation* initialUser;

@property(nonatomic) DSPlanInformation* planInformation;

@property(nonatomic) DSReferralInformation* referralInformation;

@property(nonatomic) DSSocialAccountInformation* socialAccountInformation;

@end
