#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSOfflineAttributes
@end

@interface DSOfflineAttributes : DSObject

/* A string containing information about the type of device used for offline signing. [optional]
 */
@property(nonatomic) NSString* deviceName;
/* A string containing information about the model of the device used for offline signing. [optional]
 */
@property(nonatomic) NSString* deviceModel;
/* A string containing the latitude of the device location at the time of signing. [optional]
 */
@property(nonatomic) NSString* gpsLatitude;
/* A string containing the longitude of the device location at the time of signing. [optional]
 */
@property(nonatomic) NSString* gpsLongitude;
/* A GUID identifying the account associated with the consumer disclosure [optional]
 */
@property(nonatomic) NSString* accountEsignId;
/*  [optional]
 */
@property(nonatomic) NSString* offlineSigningHash;

@end
