#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSRadio.h"


@protocol DSRadioGroup
@end

@interface DSRadioGroup : DSObject

/* For conditional fields this is the TabLabel of the parent tab that controls this tab's visibility. [optional]
 */
@property(nonatomic) NSString* conditionalParentLabel;
/* For conditional fields, this is the value of the parent tab that controls the tab's visibility.  If the parent tab is a Checkbox, Radio button, Optional Signature, or Optional Initial use \"on\" as the value to show that the parent tab is active.  [optional]
 */
@property(nonatomic) NSString* conditionalParentValue;
/* Specifies the document ID number that the tab is placed on. This must refer to an existing Document's ID attribute. [optional]
 */
@property(nonatomic) NSString* documentId;
/* The name of the group. [optional]
 */
@property(nonatomic) NSString* groupName;
/* Specifies the locations and status for radio buttons that are grouped together. [optional]
 */
@property(nonatomic) NSArray<DSRadio>* radios;
/* Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document. [optional]
 */
@property(nonatomic) NSString* recipientId;
/* When set to **true** and shared is true, information must be entered in this field to complete the envelope.  [optional]
 */
@property(nonatomic) NSString* requireAll;
/* Optional element for field markup. When set to **true**, the signer is required to initial when they modify a shared field. [optional]
 */
@property(nonatomic) NSString* requireInitialOnSharedChange;
/* When set to **true**, this custom tab is shared. [optional]
 */
@property(nonatomic) NSString* shared;

@end
