#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/




@protocol DSSettingsMetadata
@end

@interface DSSettingsMetadata : DSObject

/* When set to **true**, indicates that this module is enabled on the account. [optional]
 */
@property(nonatomic) NSString* is21CFRPart11;
/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* options;
/*  [optional]
 */
@property(nonatomic) NSString* rights;
/*  [optional]
 */
@property(nonatomic) NSString* uiHint;
/*  [optional]
 */
@property(nonatomic) NSString* uiOrder;
/*  [optional]
 */
@property(nonatomic) NSString* uiType;

@end
