#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DSLockInformation.h"
#import "DSErrorDetails.h"
#import "DSBulkEnvelopeStatus.h"


@protocol DSTemplateUpdateSummary
@end

@interface DSTemplateUpdateSummary : DSObject

/* The envelope ID of the envelope status that failed to post. [optional]
 */
@property(nonatomic) NSString* envelopeId;

@property(nonatomic) DSBulkEnvelopeStatus* bulkEnvelopeStatus;

@property(nonatomic) DSLockInformation* lockInformation;

@property(nonatomic) DSErrorDetails* errorDetails;

@end
