#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSErrorDetails.h"
#import "DSUserInfo.h"


@protocol DSUserSharedItem
@end

@interface DSUserSharedItem : DSObject


@property(nonatomic) DSErrorDetails* errorDetails;
/* When set to **true**, this custom tab is shared. [optional]
 */
@property(nonatomic) NSString* shared;

@property(nonatomic) DSUserInfo* user;

@end
