#import <Foundation/Foundation.h>
#import "DSContactGetResponse.h"
#import "DSContactModRequest.h"
#import "DSContactUpdateResponse.h"
#import "DSCustomSettingsInformation.h"
#import "DSErrorDetails.h"
#import "DSNewUsersDefinition.h"
#import "DSNewUsersSummary.h"
#import "DSUserInfoList.h"
#import "DSUserInformation.h"
#import "DSUserInformationList.h"
#import "DSUserProfile.h"
#import "DSUserSettingsInformation.h"
#import "DSUserSignature.h"
#import "DSUserSignatureDefinition.h"
#import "DSUserSignaturesInformation.h"
#import "DSUsersResponse.h"
#import "DSApi.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/















@interface DSUsersApi_GetInformationOptions : DSObject
/*
 * additionalInfo When set to **true**, the full list of user information is returned for each user in the account.
 */
@property NSString* additionalInfo;
/*
 * email 
 */
@property NSString* email;

@end




@interface DSUsersApi_GetProfileImageOptions : DSObject
/*
 * encoding 
 */
@property NSString* encoding;

@end





@interface DSUsersApi_GetSignatureImageOptions : DSObject
/*
 * includeChrome 
 */
@property NSString* includeChrome;

@end



@interface DSUsersApi_ListOptions : DSObject
/*
 * additionalInfo When set to **true**, the full list of user information is returned for each user in the account.
 */
@property NSString* additionalInfo;
/*
 * count Number of records to return. The number must be greater than 0 and less than or equal to 100. 
 */
@property NSString* count;
/*
 * email 
 */
@property NSString* email;
/*
 * emailSubstring Filters the returned user records by the email address or a sub-string of email address.
 */
@property NSString* emailSubstring;
/*
 * groupId Filters user records returned by one or more group Id&#39;s.
 */
@property NSString* groupId;
/*
 * includeUsersettingsForCsv 
 */
@property NSString* includeUsersettingsForCsv;
/*
 * loginStatus 
 */
@property NSString* loginStatus;
/*
 * notGroupId 
 */
@property NSString* notGroupId;
/*
 * startPosition Starting value for the list. 
 */
@property NSString* startPosition;
/*
 * status 
 */
@property NSString* status;
/*
 * userNameSubstring Filters the user records returned by the user name or a sub-string of user name.
 */
@property NSString* userNameSubstring;

@end











@interface DSUsersApi_UpdateSignatureOptions : DSObject
/*
 * closeExistingSignature When set to **true**, closes the current signature.
 */
@property NSString* closeExistingSignature;

@end





@interface DSUsersApi: NSObject <DSApi>

extern NSString* kDSUsersApiErrorDomain;
extern NSInteger kDSUsersApiMissingParamErrorCode;

+(instancetype) sharedAPI;

/// Adds news user to the specified account.
/// Adds new users to your account. Set the `userSettings` property in the request to specify the actions the users can perform on the account.
///
/// @param accountId The external account number (int) or account ID Guid.
/// @param varNewUsersDefinition  (optional)

///  code:201 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSNewUsersSummary*
-(NSNumber*) createWithAccountId:
(NSString*) accountId 
 varNewUsersDefinition:(DSNewUsersDefinition*) varNewUsersDefinition

 completionHandler: (void (^)(DSNewUsersSummary* output, NSError* error)) handler;

/// Adds user Signature and initials images to a Signature.
/// Adds a user signature image and/or user initials image to the specified user.   The userId property specified in the endpoint must match the authenticated user's userId and the user must be a member of the account.  The rules and processes associated with this are:  * If Content-Type is set to application/json, then the default behavior for creating a default signature image, based on the name and a DocuSign font, is used. * If Content-Type is set to multipart/form-data, then the request must contain a first part with the user signature information, followed by parts that contain the images.  For each Image part, the Content-Disposition header has a \"filename\" value that is used to map to the `signatureName` and/or `signatureInitials` properties in the JSON to the image.   For example:  `Content-Disposition: file; filename=\"Ron Test20121127083900\"`  If no matching image (by filename value) is found, then the image is not set. One, both, or neither of the signature and initials images can be set with this call.  The Content-Transfer-Encoding: base64 header, set in the header for the part containing the image, can be set to indicate that the images are formatted as base64 instead of as binary.  If successful, 200-OK is returned, and a JSON structure containing the signature information is provided, note that the signatureId can change with each API POST, PUT, or DELETE since the changes to the signature structure cause the current signature to be closed, and a new signature record to be created.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
/// @param userSignaturesInformation  (optional)

///  code:201 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserSignaturesInformation*
-(NSNumber*) createSignaturesWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 userSignaturesInformation:(DSUserSignaturesInformation*) userSignaturesInformation

 completionHandler: (void (^)(DSUserSignaturesInformation* output, NSError* error)) handler;

/// Removes users account privileges.
/// This closes one or more user records in the account. Users are never deleted from an account, but closing a user prevents them from using account functions.  The response returns whether the API execution was successful (200 - OK) or  if it failed. The response contains a user structure similar to the request and includes the user changes. If an error occurred during the DELETE operation for any of the users, the response for that user contains an `errorDetails` node with `errorCode` and `message` properties.
///
/// @param accountId The external account number (int) or account ID Guid.
/// @param userInfoList  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUsersResponse*
-(NSNumber*) deleteWithAccountId:
(NSString*) accountId 
 userInfoList:(DSUserInfoList*) userInfoList

 completionHandler: (void (^)(DSUsersResponse* output, NSError* error)) handler;

/// Replaces a particular contact associated with an account for the DocuSign service.
///
/// @param accountId The external account number (int) or account ID Guid./// @param contactId The unique identifier of a person in the contacts address book.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSContactUpdateResponse*
-(NSNumber*) deleteContactWithIdWithAccountId:
(NSString*) accountId  contactId:(NSString*) contactId 


 completionHandler: (void (^)(DSContactUpdateResponse* output, NSError* error)) handler;

/// Delete contacts associated with an account for the DocuSign service.
///
/// @param accountId The external account number (int) or account ID Guid.
/// @param contactModRequest  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSContactUpdateResponse*
-(NSNumber*) deleteContactsWithAccountId:
(NSString*) accountId 
 contactModRequest:(DSContactModRequest*) contactModRequest

 completionHandler: (void (^)(DSContactUpdateResponse* output, NSError* error)) handler;

/// Deletes custom user settings for a specified user.
/// Deletes the specified custom user settings for a single user.  ###Deleting Grouped Custom User Settings###  If the custom user settings you want to delete are grouped, you must include the following information in the header, after Content-Type, in the request:  `X-DocuSign-User-Settings-Key:group_name`  Where the `group_name` is your designated name for the group of customer user settings.  If the extra header information is not included, only the custom user settings that were added without a group are deleted.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
/// @param customSettingsInformation  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSCustomSettingsInformation*
-(NSNumber*) deleteCustomSettingsWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 customSettingsInformation:(DSCustomSettingsInformation*) customSettingsInformation

 completionHandler: (void (^)(DSCustomSettingsInformation* output, NSError* error)) handler;

/// Deletes the user profile image for the specified user.
/// Deletes the user profile image from the  specified user's profile.  The userId parameter specified in the endpoint must match the authenticated user's user ID and the user must be a member of the specified account.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
-(NSNumber*) deleteProfileImageWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 


 completionHandler: (void (^)(NSError* error)) handler;

/// Removes removes signature information for the specified user.
/// Removes the signature information for the user.  The userId parameter specified in the endpoint must match the authenticated user's user ID and the user must be a member of the account.  The `signatureId` accepts a signature ID or a signature name. DocuSign recommends you use signature ID (`signatureId`), since some names contain characters that do not properly encode into a URL. If you use the user name, it is likely that the name includes spaces. In that case, URL encode the name before using it in the endpoint.   For example encode \"Bob Smith\" as \"Bob%20Smith\".
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing./// @param signatureId The ID of the signature being accessed.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
-(NSNumber*) deleteSignatureWithAccountId:
(NSString*) accountId  userId:(NSString*) userId  signatureId:(NSString*) signatureId 


 completionHandler: (void (^)(NSError* error)) handler;

/// Deletes the user initials image or the  user signature image for the specified user.
/// Deletes the specified initials image or signature image for the specified user.  The function deletes one or the other of the image types, to delete both the initials image and signature image you must call the endpoint twice.  The userId parameter specified in the endpoint must match the authenticated user's user ID and the user must be a member of the account.  The `signatureId` parameter accepts a signature ID or a signature name. DocuSign recommends you use signature ID (`signatureId`), since some names contain characters that do not properly encode into a URL. If you use the user name, it is likely that the name includes spaces. In that case, URL encode the name before using it in the endpoint.   For example encode \"Bob Smith\" as \"Bob%20Smith\".
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing./// @param signatureId The ID of the signature being accessed./// @param imageType One of **signature_image** or **initials_image**.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserSignature*
-(NSNumber*) deleteSignatureImageWithAccountId:
(NSString*) accountId  userId:(NSString*) userId  signatureId:(NSString*) signatureId  imageType:(NSString*) imageType 


 completionHandler: (void (^)(DSUserSignature* output, NSError* error)) handler;

/// Gets a particular contact associated with the user's account.
///
/// @param accountId The external account number (int) or account ID Guid./// @param contactId The unique identifier of a person in the contacts address book.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSContactGetResponse*
-(NSNumber*) getContactByIdWithAccountId:
(NSString*) accountId  contactId:(NSString*) contactId 


 completionHandler: (void (^)(DSContactGetResponse* output, NSError* error)) handler;

/// Gets the user information for a specified user.
/// Retrieves the user information for the specified user.   To return additional user information that details the last login date, login status, and the user's password expiration date, set the optional `additional_info` query string parameter to **true**.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.

/// @param DSUsersApi_GetInformationOptions Options for modifying the behavior of the function.
///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserInformation*
-(NSNumber*) getInformationWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 

 options:(DSUsersApi_GetInformationOptions*) options
 completionHandler: (void (^)(DSUserInformation* output, NSError* error)) handler;

/// Retrieves the user profile for a specified user.
/// Retrieves the user profile information, the privacy settings and personal information (address, phone number, etc.) for the specified user.  The userId parameter specified in the endpoint must match the authenticated user's user ID and the user must be a member of the specified account.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserProfile*
-(NSNumber*) getProfileWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 


 completionHandler: (void (^)(DSUserProfile* output, NSError* error)) handler;

/// Retrieves the user profile image for the specified user.
/// Retrieves the user profile picture for the specified user. The image is returned in the same format as uploaded.  The userId parameter specified in the endpoint must match the authenticated user's user ID and the user must be a member of the specified account.  If successful, the response returns a 200 - OK and the user profile image.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.

/// @param DSUsersApi_GetProfileImageOptions Options for modifying the behavior of the function.
///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return NSURL*
-(NSNumber*) getProfileImageWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 

 options:(DSUsersApi_GetProfileImageOptions*) options
 completionHandler: (void (^)(NSURL* output, NSError* error)) handler;

/// Gets the user account settings for a specified user.
/// Retrieves a list of the account settings and email notification information for the specified user.  The response returns the account setting name/value information and the email notification settings for the specified user. For more information about the different user settings, see the [ML:userSettings list].
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserSettingsInformation*
-(NSNumber*) getSettingsWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 


 completionHandler: (void (^)(DSUserSettingsInformation* output, NSError* error)) handler;

/// Gets the user signature information for the specified user.
/// Retrieves the structure of a single signature with a known signature name.  The userId specified in the endpoint must match the authenticated user's user ID and the user must be a member of the account.  The `signatureId` parameter accepts a signature ID or a signature name. DocuSign recommends you use signature ID (`signatureId`), since some names contain characters that do not properly encode into a URL. If you use the user name, it is likely that the name includes spaces. In that case, URL encode the name before using it in the endpoint.   For example encode \"Bob Smith\" as \"Bob%20Smith\".
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing./// @param signatureId The ID of the signature being accessed.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserSignature*
-(NSNumber*) getSignatureWithAccountId:
(NSString*) accountId  userId:(NSString*) userId  signatureId:(NSString*) signatureId 


 completionHandler: (void (^)(DSUserSignature* output, NSError* error)) handler;

/// Retrieves the user initials image or the  user signature image for the specified user.
/// Retrieves the specified initials image or signature image for the specified user. The image is returned in the same format as uploaded. In the request you can specify if the chrome (the added line and identifier around the initial image) is returned with the image.  The userId property specified in the endpoint must match the authenticated user's user ID and the user must be a member of the account.  The `signatureId` parameter accepts a signature ID or a signature name. DocuSign recommends you use signature ID (`signatureId`), since some names contain characters that do not properly encode into a URL. If you use the user name, it is likely that the name includes spaces. In that case, URL encode the name before using it in the endpoint.   For example encode \"Bob Smith\" as \"Bob%20Smith\".  ###### Note: Older envelopes might only have chromed images. If getting the non-chromed image fails, try getting the chromed image.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing./// @param signatureId The ID of the signature being accessed./// @param imageType One of **signature_image** or **initials_image**.

/// @param DSUsersApi_GetSignatureImageOptions Options for modifying the behavior of the function.
///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return NSURL*
-(NSNumber*) getSignatureImageWithAccountId:
(NSString*) accountId  userId:(NSString*) userId  signatureId:(NSString*) signatureId  imageType:(NSString*) imageType 

 options:(DSUsersApi_GetSignatureImageOptions*) options
 completionHandler: (void (^)(NSURL* output, NSError* error)) handler;

/// Retrieves the list of users for the specified account.
/// Retrieves the list of users for the specified account.  The response returns the list of users for the account along with the information about the result set. If the `additional_info` query was added to the endpoint and set to **true**, the full user information is returned for each user
///
/// @param accountId The external account number (int) or account ID Guid.

/// @param DSUsersApi_ListOptions Options for modifying the behavior of the function.
///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserInformationList*
-(NSNumber*) listWithAccountId:
(NSString*) accountId 

 options:(DSUsersApi_ListOptions*) options
 completionHandler: (void (^)(DSUserInformationList* output, NSError* error)) handler;

/// Retrieves the custom user settings for a specified user.
/// Retrieves a list of custom user settings for a single user.  Custom settings provide a flexible way to store and retrieve custom user information that can be used in your own system.  ###### Note: Custom user settings are not the same as user account settings.  ###Getting Grouped Custom User Settings###  If the custom user settings you want to retrieve are grouped, you must include the following information in the header, after Content-Type, in the request:  `X-DocuSign-User-Settings-Key:group_name`  Where the `group_name` is your designated name for the group of customer user settings.  If the extra header information is not included, only the custom user settings that were added without a group are retrieved.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSCustomSettingsInformation*
-(NSNumber*) listCustomSettingsWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 


 completionHandler: (void (^)(DSCustomSettingsInformation* output, NSError* error)) handler;

/// Retrieves a list of user signature definitions for a specified user.
/// Retrieves the signature definitions for the specified user.  The userId parameter specified in the endpoint must match the authenticated user's user ID and the user must be a member of the account.  The `signatureId` parameter accepts a signature ID or a signature name. DocuSign recommends you use signature ID (`signatureId`), since some names contain characters that do not properly encode into a URL. If you use the user name, it is likely that the name includes spaces. In that case, URL encode the name before using it in the endpoint.   For example encode \"Bob Smith\" as \"Bob%20Smith\".
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserSignaturesInformation*
-(NSNumber*) listSignaturesWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 


 completionHandler: (void (^)(DSUserSignaturesInformation* output, NSError* error)) handler;

/// Imports multiple new contacts into the contacts collection from CSV, JSON, or XML (based on content type).
///
/// @param accountId The external account number (int) or account ID Guid.
/// @param contactModRequest  (optional)

///  code:201 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSContactUpdateResponse*
-(NSNumber*) postContactsWithAccountId:
(NSString*) accountId 
 contactModRequest:(DSContactModRequest*) contactModRequest

 completionHandler: (void (^)(DSContactUpdateResponse* output, NSError* error)) handler;

/// Replaces contacts associated with an account for the DocuSign service.
///
/// @param accountId The external account number (int) or account ID Guid.
/// @param contactModRequest  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSContactUpdateResponse*
-(NSNumber*) putContactsWithAccountId:
(NSString*) accountId 
 contactModRequest:(DSContactModRequest*) contactModRequest

 completionHandler: (void (^)(DSContactUpdateResponse* output, NSError* error)) handler;

/// Adds or updates custom user settings for the specified user.
/// Adds or updates custom user settings for the specified user.  ###### Note: Custom user settings are not the same as user account settings.  Custom settings provide a flexible way to store and retrieve custom user information that you can use in your own system.  **Important**: There is a limit on the size for all the custom user settings for a single user. The limit is 4,000 characters, which includes the XML and JSON structure for the settings.  ### Grouping Custom User Settings ###  You can group custom user settings when adding them. Grouping allows you to retrieve settings that are in a specific group, instead of retrieving all the user custom settings.  To group custom user settings, add the following information in the header, after Content-Type:  `X-DocuSign-User-Settings-Key:group_name`  Where the `group_name` is your designated name for the group of customer user settings. Grouping is shown in the Example Request Body below.  When getting or deleting grouped custom user settings, you must include the extra header information.  Grouping custom user settings is not required and if the extra header information is not included, the custom user settings are added normally and can be retrieved or deleted without including the additional header.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
/// @param customSettingsInformation  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSCustomSettingsInformation*
-(NSNumber*) updateCustomSettingsWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 customSettingsInformation:(DSCustomSettingsInformation*) customSettingsInformation

 completionHandler: (void (^)(DSCustomSettingsInformation* output, NSError* error)) handler;

/// Updates the user profile information for the specified user.
/// Updates the user's detail information, profile information, privacy settings, and personal information in the user ID card.  You can also change a user's name by changing the information in the `userDetails` property. When changing a user's name, you can either change the information in the `userName` property OR change the information in `firstName`, `middleName`, `lastName, suffixName`, and `title` properties. Changes to `firstName`, `middleName`, `lastName`, `suffixName`, and `title` properties take precedence over changes to the `userName` property.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
/// @param userProfile  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
-(NSNumber*) updateProfileWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 userProfile:(DSUserProfile*) userProfile

 completionHandler: (void (^)(NSError* error)) handler;

/// Updates the user profile image for a specified user.
/// Updates the user profile image by uploading an image to the user profile.  The supported image formats are: gif, png, jpeg, and bmp. The file must be less than 200K. For best viewing results, DocuSign recommends that the image is no more than 79 pixels wide and high.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
-(NSNumber*) updateProfileImageWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 


 completionHandler: (void (^)(NSError* error)) handler;

/// Updates the user account settings for a specified user.
/// Updates the account settings list and email notification types for the specified user.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
/// @param userSettingsInformation  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
-(NSNumber*) updateSettingsWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 userSettingsInformation:(DSUserSettingsInformation*) userSettingsInformation

 completionHandler: (void (^)(NSError* error)) handler;

/// Updates the user signature for a specified user.
/// Creates, or updates, the signature font and initials for the specified user. When creating a signature, you use this resource to create the signature name and then add the signature and initials images into the signature.  ###### Note: This will also create a default signature for the user when one does not exist.  The userId property specified in the endpoint must match the authenticated user's user ID and the user must be a member of the account.  The `signatureId` parameter accepts a signature ID or a signature name. DocuSign recommends you use signature ID (`signatureId`), since some names contain characters that do not properly encode into a URL. If you use the user name, it is likely that the name includes spaces. In that case, URL encode the name before using it in the endpoint.   For example encode \"Bob Smith\" as \"Bob%20Smith\".
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing./// @param signatureId The ID of the signature being accessed.
/// @param userSignatureDefinition  (optional)
/// @param DSUsersApi_UpdateSignatureOptions Options for modifying the behavior of the function.
///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserSignature*
-(NSNumber*) updateSignatureWithAccountId:
(NSString*) accountId  userId:(NSString*) userId  signatureId:(NSString*) signatureId 
 userSignatureDefinition:(DSUserSignatureDefinition*) userSignatureDefinition
 options:(DSUsersApi_UpdateSignatureOptions*) options
 completionHandler: (void (^)(DSUserSignature* output, NSError* error)) handler;

/// Updates the user signature image or user initials image for the specified user.
/// Updates the user signature image or user initials image for the specified user. The supported image formats for this file are: gif, png, jpeg, and bmp. The file must be less than 200K.  The userId property specified in the endpoint must match the authenticated user's user ID and the user must be a member of the account.  The `signatureId` parameter accepts a signature ID or a signature name. DocuSign recommends you use signature ID (`signatureId`), since some names contain characters that do not properly encode into a URL. If you use the user name, it is likely that the name includes spaces. In that case, URL encode the name before using it in the endpoint.   For example encode \"Bob Smith\" as \"Bob%20Smith\". 
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing./// @param signatureId The ID of the signature being accessed./// @param imageType One of **signature_image** or **initials_image**.


///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserSignature*
-(NSNumber*) updateSignatureImageWithAccountId:
(NSString*) accountId  userId:(NSString*) userId  signatureId:(NSString*) signatureId  imageType:(NSString*) imageType 


 completionHandler: (void (^)(DSUserSignature* output, NSError* error)) handler;

/// Updates the specified user information.
///
/// @param accountId The external account number (int) or account ID Guid./// @param userId The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
/// @param userInformation  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserInformation*
-(NSNumber*) updateUserWithAccountId:
(NSString*) accountId  userId:(NSString*) userId 
 userInformation:(DSUserInformation*) userInformation

 completionHandler: (void (^)(DSUserInformation* output, NSError* error)) handler;

/// Change one or more user in the specified account.
///
/// @param accountId The external account number (int) or account ID Guid.
/// @param userInformationList  (optional)

///  code:200 message:"Successful response.",
///  code:400 message:"Error encountered."
/// @return DSUserInformationList*
-(NSNumber*) updateUsersWithAccountId:
(NSString*) accountId 
 userInformationList:(DSUserInformationList*) userInformationList

 completionHandler: (void (^)(DSUserInformationList* output, NSError* error)) handler;


@end
