#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSErrorDetails.h"


@protocol DSWorkspaceUser
@end

@interface DSWorkspaceUser : DSObject

/* The account ID associated with the envelope. [optional]
 */
@property(nonatomic) NSString* accountId;
/* The name of the account that the workspace user belongs to. [optional]
 */
@property(nonatomic) NSString* accountName;
/*  [optional]
 */
@property(nonatomic) NSString* activeSince;
/* The UTC DateTime when the workspace user was created. [optional]
 */
@property(nonatomic) NSString* created;
/*  [optional]
 */
@property(nonatomic) NSString* createdById;
/*  [optional]
 */
@property(nonatomic) NSString* email;

@property(nonatomic) DSErrorDetails* errorDetails;
/* Utc date and time the comment was last updated (can only be done by creator.) [optional]
 */
@property(nonatomic) NSString* lastModified;
/*  [optional]
 */
@property(nonatomic) NSString* lastModifiedById;
/* Indicates the envelope status. Valid values are:  * sent - The envelope is sent to the recipients.  * created - The envelope is saved as a draft and can be modified and sent later. [optional]
 */
@property(nonatomic) NSString* status;
/* Type of the user. Valid values: type_owner, type_participant. [optional]
 */
@property(nonatomic) NSString* type;
/*  [optional]
 */
@property(nonatomic) NSString* userId;
/*  [optional]
 */
@property(nonatomic) NSString* userName;
/*  [optional]
 */
@property(nonatomic) NSString* workspaceId;
/* The relative URI that may be used to access a workspace user. [optional]
 */
@property(nonatomic) NSString* workspaceUserBaseUrl;
/*  [optional]
 */
@property(nonatomic) NSString* workspaceUserId;

@end
