#target 'SdkTestsTests' do
#  pod "DocuSignESign", :path => "../../sdk"
#end


platform :ios, '9.0'
target 'SdkTestsTests' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "DocuSignESign", :path => "../../sdk"
end
