#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "DSErrorDetails.h"


@protocol DSListCustomField
@end

@interface DSListCustomField : DSObject

/*  [optional]
 */
@property(nonatomic) NSArray* /* NSString */ listItems;
/* An ID used to specify a custom field. [optional]
 */
@property(nonatomic) NSString* fieldId;
/* The name of the custom field. [optional]
 */
@property(nonatomic) NSString* name;
/* A boolean indicating if the value should be displayed. [optional]
 */
@property(nonatomic) NSString* show;
/* When set to **true**, the signer is required to fill out this tab [optional]
 */
@property(nonatomic) NSString* required;
/* The value of the custom field.\n\nMaximum Length: 100 characters. [optional]
 */
@property(nonatomic) NSString* value;
/*  [optional]
 */
@property(nonatomic) NSString* configurationType;

@property(nonatomic) DSErrorDetails* errorDetails;

@end
