#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSSocialAuthentication
@end

@interface DSSocialAuthentication : DSObject

/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* authentication;

@end
