#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol DSViewUrl
@end

@interface DSViewUrl : DSObject

/* The view URL to be navigated to. [optional]
 */
@property(nonatomic) NSString* url;

@end
