#import <Foundation/Foundation.h>
#import "DSObject.h"

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "DSErrorDetails.h"


@protocol DSCustomField
@end

@interface DSCustomField : DSObject

/*  [optional]
 */
@property(nonatomic) NSString* customFieldType;

@property(nonatomic) DSErrorDetails* errorDetails;
/*  [optional]
 */
@property(nonatomic) NSString* fieldId;
/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* listItems;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/* When set to **true**, the signer is required to fill out this tab [optional]
 */
@property(nonatomic) NSString* required;
/*  [optional]
 */
@property(nonatomic) NSString* show;
/* Specifies the value of the tab.  [optional]
 */
@property(nonatomic) NSString* value;

@end
