#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol DSESReportInProductRunResponseRowFields
@end

@interface DSESReportInProductRunResponseRowFields : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* accessCodeRequired;
/*  [optional]
 */
@property(nonatomic) NSString* accessCodesAttempted;
/*  [optional]
 */
@property(nonatomic) NSString* accessCodesFailed;
/* The account ID associated with the envelope. [optional]
 */
@property(nonatomic) NSString* accountId;
/*  [optional]
 */
@property(nonatomic) NSString* authenticationCategory;
/*  [optional]
 */
@property(nonatomic) NSString* authenticationSuccess;
/*  [optional]
 */
@property(nonatomic) NSString* authenticationType;
/*  [optional]
 */
@property(nonatomic) NSString* averageTimeToCompleteSeconds;
/*  [optional]
 */
@property(nonatomic) NSString* avgCompleteSeconds;
/*  [optional]
 */
@property(nonatomic) NSString* completed;
/*  [optional]
 */
@property(nonatomic) NSString* completedTs;
/*  [optional]
 */
@property(nonatomic) NSString* createdDate;
/*  [optional]
 */
@property(nonatomic) NSString* customField;
/*  [optional]
 */
@property(nonatomic) NSString* declinedDate;
/* The reason the recipient declined the document. [optional]
 */
@property(nonatomic) NSString* declinedReason;
/*  [optional]
 */
@property(nonatomic) NSString* deliveredDate;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeCount;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeCreator;
/* The envelope ID of the envelope status that failed to post. [optional]
 */
@property(nonatomic) NSString* envelopeId;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeInitialSendTs;
/*  [optional]
 */
@property(nonatomic) NSString* envelopesBilled;
/*  [optional]
 */
@property(nonatomic) NSString* envelopesCompleted;
/*  [optional]
 */
@property(nonatomic) NSString* envelopesCompletedCount;
/*  [optional]
 */
@property(nonatomic) NSString* envelopesDeclined;
/*  [optional]
 */
@property(nonatomic) NSString* envelopesSent;
/*  [optional]
 */
@property(nonatomic) NSString* envelopesSentCount;
/*  [optional]
 */
@property(nonatomic) NSString* envelopesVoided;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeVoidedReason;
/*  [optional]
 */
@property(nonatomic) NSString* eodDocumentDescription;
/*  [optional]
 */
@property(nonatomic) NSString* eodDocumentName;
/*  [optional]
 */
@property(nonatomic) NSString* eodDocumentProfileId;
/*  [optional]
 */
@property(nonatomic) NSString* eodTransactionId;
/*  [optional]
 */
@property(nonatomic) NSString* eodTransactionName;
/*  [optional]
 */
@property(nonatomic) NSString* eventDate;
/*  [optional]
 */
@property(nonatomic) NSString* expirationDate;
/*  [optional]
 */
@property(nonatomic) NSString* expiredTs;
/*  [optional]
 */
@property(nonatomic) NSString* failures;
/*  [optional]
 */
@property(nonatomic) NSString* failureVendorCode;
/*  [optional]
 */
@property(nonatomic) NSString* failureVendorReason;
/*  [optional]
 */
@property(nonatomic) NSString* firstSendTs;
/*  [optional]
 */
@property(nonatomic) NSString* groupId;
/* The name of the group. [optional]
 */
@property(nonatomic) NSString* groupName;
/*  [optional]
 */
@property(nonatomic) NSString* hoursToCompleteEnd;
/*  [optional]
 */
@property(nonatomic) NSString* hoursToCompleteStart;
/*  [optional]
 */
@property(nonatomic) NSString* idChecksAttempted;
/*  [optional]
 */
@property(nonatomic) NSString* idChecksFailed;
/*  [optional]
 */
@property(nonatomic) NSString* initialSendTs;
/*  [optional]
 */
@property(nonatomic) NSString* ipAddress;
/*  [optional]
 */
@property(nonatomic) NSString* lastActivity;
/*  [optional]
 */
@property(nonatomic) NSString* lastActivityDate;
/*  [optional]
 */
@property(nonatomic) NSString* lastSentDate;
/*  [optional]
 */
@property(nonatomic) NSString* notSigned;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfAuthenticatedRecipients;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfCompletedSignatures;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfDocuments;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfPages;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfRecipients;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfSends;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfSigners;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfTotalDocuments;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfTotalPages;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfTotalSigners;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfUniqueSenders;
/*  [optional]
 */
@property(nonatomic) NSString* numberTotalRecipients;
/*  [optional]
 */
@property(nonatomic) NSString* periodEnd;
/*  [optional]
 */
@property(nonatomic) NSString* periodStart;
/*  [optional]
 */
@property(nonatomic) NSString* phoneCallsAttempted;
/*  [optional]
 */
@property(nonatomic) NSString* phoneCallsFailed;
/*  [optional]
 */
@property(nonatomic) NSString* reasonForDeclining;
/*  [optional]
 */
@property(nonatomic) NSString* reasonForVoiding;
/*  [optional]
 */
@property(nonatomic) NSString* reassignReason;
/*  [optional]
 */
@property(nonatomic) NSString* received;
/*  [optional]
 */
@property(nonatomic) NSString* recipient;
/*  [optional]
 */
@property(nonatomic) NSString* recipientAction;
/*  [optional]
 */
@property(nonatomic) NSString* recipientCompanyName;
/*  [optional]
 */
@property(nonatomic) NSString* recipientCountry;
/*  [optional]
 */
@property(nonatomic) NSString* recipientEmail;
/* Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document. [optional]
 */
@property(nonatomic) NSString* recipientId;
/*  [optional]
 */
@property(nonatomic) NSString* recipientName;
/*  [optional]
 */
@property(nonatomic) NSString* recipientTemplateRoleName;
/*  [optional]
 */
@property(nonatomic) NSString* recipientTitle;
/*  [optional]
 */
@property(nonatomic) NSString* recipientType;
/*  [optional]
 */
@property(nonatomic) NSString* recipientUserId;
/*  [optional]
 */
@property(nonatomic) NSString* remainingSignatures;
/* Specifies the routing order of the recipient in the envelope.  [optional]
 */
@property(nonatomic) NSString* routingOrder;
/*  [optional]
 */
@property(nonatomic) NSString* senderAccountId;
/*  [optional]
 */
@property(nonatomic) NSString* senderCompanyName;
/*  [optional]
 */
@property(nonatomic) NSString* senderCountry;
/*  [optional]
 */
@property(nonatomic) NSString* senderEmail;
/*  [optional]
 */
@property(nonatomic) NSString* senderIPAddress;
/*  [optional]
 */
@property(nonatomic) NSString* senderJobTitle;
/*  [optional]
 */
@property(nonatomic) NSString* senderName;
/*  [optional]
 */
@property(nonatomic) NSString* senderUserId;
/*  [optional]
 */
@property(nonatomic) NSString* signDate;
/*  [optional]
 */
@property(nonatomic) NSString* _signed;
/*  [optional]
 */
@property(nonatomic) NSString* signedDate;
/*  [optional]
 */
@property(nonatomic) NSString* signedOnMobile;
/*  [optional]
 */
@property(nonatomic) NSString* signedOnPaper;
/*  [optional]
 */
@property(nonatomic) NSString* signerList;
/* Indicates the envelope status. Valid values are:  * sent - The envelope is sent to the recipients.  * created - The envelope is saved as a draft and can be modified and sent later. [optional]
 */
@property(nonatomic) NSString* status;
/*  [optional]
 */
@property(nonatomic) NSString* statusChangedDate;
/*  [optional]
 */
@property(nonatomic) NSString* statusChangedTs;
/*  [optional]
 */
@property(nonatomic) NSString* subject;
/*  [optional]
 */
@property(nonatomic) NSString* successes;
/*  [optional]
 */
@property(nonatomic) NSString* templatesCreated;
/*  [optional]
 */
@property(nonatomic) NSString* templatesCreatedCount;
/*  [optional]
 */
@property(nonatomic) NSString* terminalStatusDate;
/*  [optional]
 */
@property(nonatomic) NSString* timeToCompleteSeconds;
/*  [optional]
 */
@property(nonatomic) NSString* timeToDeliver;
/*  [optional]
 */
@property(nonatomic) NSString* totalDocuments;
/*  [optional]
 */
@property(nonatomic) NSString* totalEnvelopes;
/*  [optional]
 */
@property(nonatomic) NSString* totalPages;
/*  [optional]
 */
@property(nonatomic) NSString* totalRecipients;
/*  [optional]
 */
@property(nonatomic) NSString* totalSigners;
/*  [optional]
 */
@property(nonatomic) NSString* uniqueSenders;
/*  [optional]
 */
@property(nonatomic) NSString* userAccountEmail;
/*  [optional]
 */
@property(nonatomic) NSString* userAccountName;
/*  [optional]
 */
@property(nonatomic) NSString* userAccountStatus;
/*  [optional]
 */
@property(nonatomic) NSString* userCount;
/*  [optional]
 */
@property(nonatomic) NSString* userId;
/*  [optional]
 */
@property(nonatomic) NSString* viewDate;
/*  [optional]
 */
@property(nonatomic) NSString* voidedTs;

@end
