#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESServiceVersion.h>
@protocol DSESServiceVersion;
@class DSESServiceVersion;



@protocol DSESServiceInformation
@end

@interface DSESServiceInformation : DSESObject

/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* buildBranch;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* buildBranchDeployedDateTime;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* buildSHA;
/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* buildVersion;
/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* linkedSites;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESServiceVersion>* serviceVersions;

@end
