#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESWorkspaceSettings.h>
#import <DSESWorkspaceUser.h>
@protocol DSESWorkspaceSettings;
@class DSESWorkspaceSettings;
@protocol DSESWorkspaceUser;
@class DSESWorkspaceUser;



@protocol DSESWorkspace
@end

@interface DSESWorkspace : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* billableAccountId;

@property(nonatomic) DSESWorkspaceUser* callerInformation;
/*  [optional]
 */
@property(nonatomic) NSString* created;

@property(nonatomic) DSESWorkspaceUser* createdByInformation;
/* Utc date and time the comment was last updated (can only be done by creator.) [optional]
 */
@property(nonatomic) NSString* lastModified;

@property(nonatomic) DSESWorkspaceUser* lastModifiedByInformation;

@property(nonatomic) DSESWorkspaceSettings* settings;
/* Indicates the envelope status. Valid values are:  * sent - The envelope is sent to the recipients.  * created - The envelope is saved as a draft and can be modified and sent later. [optional]
 */
@property(nonatomic) NSString* status;
/* The relative URL that may be used to access the workspace. [optional]
 */
@property(nonatomic) NSString* workspaceBaseUrl;
/* Text describing the purpose of the workspace. [optional]
 */
@property(nonatomic) NSString* workspaceDescription;
/* The id of the workspace, always populated. [optional]
 */
@property(nonatomic) NSString* workspaceId;
/* The name of the workspace. [optional]
 */
@property(nonatomic) NSString* workspaceName;
/* The relative URI that may be used to access the workspace. [optional]
 */
@property(nonatomic) NSString* workspaceUri;

@end
