#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESErrorDetails.h>
#import <DSESFolderSharedItem.h>
#import <DSESSharedItem.h>
#import <DSESTemplateSharedItem.h>
#import <DSESUserInfo.h>
@protocol DSESErrorDetails;
@class DSESErrorDetails;
@protocol DSESFolderSharedItem;
@class DSESFolderSharedItem;
@protocol DSESSharedItem;
@class DSESSharedItem;
@protocol DSESTemplateSharedItem;
@class DSESTemplateSharedItem;
@protocol DSESUserInfo;
@class DSESUserInfo;



@protocol DSESMemberSharedItems
@end

@interface DSESMemberSharedItems : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray<DSESSharedItem>* envelopes;

@property(nonatomic) DSESErrorDetails* errorDetails;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESFolderSharedItem>* folders;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESTemplateSharedItem>* templates;

@property(nonatomic) DSESUserInfo* user;

@end
