#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESAccountAddress.h>
#import <DSESAccountSettingsInformation.h>
#import <DSESCreditCardInformation.h>
#import <DSESDirectDebitProcessorInformation.h>
#import <DSESPaymentProcessorInformation.h>
#import <DSESPlanInformation.h>
#import <DSESReferralInformation.h>
#import <DSESSocialAccountInformation.h>
#import <DSESUserInformation.h>
@protocol DSESAccountAddress;
@class DSESAccountAddress;
@protocol DSESAccountSettingsInformation;
@class DSESAccountSettingsInformation;
@protocol DSESCreditCardInformation;
@class DSESCreditCardInformation;
@protocol DSESDirectDebitProcessorInformation;
@class DSESDirectDebitProcessorInformation;
@protocol DSESPaymentProcessorInformation;
@class DSESPaymentProcessorInformation;
@protocol DSESPlanInformation;
@class DSESPlanInformation;
@protocol DSESReferralInformation;
@class DSESReferralInformation;
@protocol DSESSocialAccountInformation;
@class DSESSocialAccountInformation;
@protocol DSESUserInformation;
@class DSESUserInformation;



@protocol DSESNewAccountDefinition
@end

@interface DSESNewAccountDefinition : DSESObject

/* The account name for the new account. [optional]
 */
@property(nonatomic) NSString* accountName;

@property(nonatomic) DSESAccountSettingsInformation* accountSettings;

@property(nonatomic) DSESAccountAddress* addressInformation;

@property(nonatomic) DSESCreditCardInformation* creditCardInformation;

@property(nonatomic) DSESDirectDebitProcessorInformation* directDebitProcessorInformation;
/* The code that identifies the billing plan groups and plans for the new account. [optional]
 */
@property(nonatomic) NSString* distributorCode;
/* The password for the distributorCode. [optional]
 */
@property(nonatomic) NSString* distributorPassword;
/*  [optional]
 */
@property(nonatomic) NSString* envelopePartitionId;

@property(nonatomic) DSESUserInformation* initialUser;
/*  [optional]
 */
@property(nonatomic) NSString* paymentMethod;

@property(nonatomic) DSESPaymentProcessorInformation* paymentProcessorInformation;

@property(nonatomic) DSESPlanInformation* planInformation;

@property(nonatomic) DSESReferralInformation* referralInformation;

@property(nonatomic) DSESSocialAccountInformation* socialAccountInformation;

@end
