#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESErrorDetails.h>
#import <DSESPropertyMetadata.h>
@protocol DSESErrorDetails;
@class DSESErrorDetails;
@protocol DSESPropertyMetadata;
@class DSESPropertyMetadata;



@protocol DSESRadio
@end

@interface DSESRadio : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* anchorAllowWhiteSpaceInCharacters;

@property(nonatomic) DSESPropertyMetadata* anchorAllowWhiteSpaceInCharactersMetadata;
/* When set to **true**, the anchor string does not consider case when matching strings in the document. The default value is **true**. [optional]
 */
@property(nonatomic) NSString* anchorCaseSensitive;

@property(nonatomic) DSESPropertyMetadata* anchorCaseSensitiveMetadata;
/* Specifies the alignment of anchor tabs with anchor strings. Possible values are **left** or **right**. The default value is **left**. [optional]
 */
@property(nonatomic) NSString* anchorHorizontalAlignment;

@property(nonatomic) DSESPropertyMetadata* anchorHorizontalAlignmentMetadata;
/* When set to **true**, this tab is ignored if anchorString is not found in the document. [optional]
 */
@property(nonatomic) NSString* anchorIgnoreIfNotPresent;

@property(nonatomic) DSESPropertyMetadata* anchorIgnoreIfNotPresentMetadata;
/* When set to **true**, the anchor string in this tab matches whole words only (strings embedded in other strings are ignored.) The default value is **true**. [optional]
 */
@property(nonatomic) NSString* anchorMatchWholeWord;

@property(nonatomic) DSESPropertyMetadata* anchorMatchWholeWordMetadata;
/* Anchor text information for a radio button. [optional]
 */
@property(nonatomic) NSString* anchorString;

@property(nonatomic) DSESPropertyMetadata* anchorStringMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* anchorTabProcessorVersion;

@property(nonatomic) DSESPropertyMetadata* anchorTabProcessorVersionMetadata;
/* Specifies units of the X and Y offset. Units could be pixels, millimeters, centimeters, or inches. [optional]
 */
@property(nonatomic) NSString* anchorUnits;

@property(nonatomic) DSESPropertyMetadata* anchorUnitsMetadata;
/* Specifies the X axis location of the tab, in anchorUnits, relative to the anchorString. [optional]
 */
@property(nonatomic) NSString* anchorXOffset;

@property(nonatomic) DSESPropertyMetadata* anchorXOffsetMetadata;
/* Specifies the Y axis location of the tab, in anchorUnits, relative to the anchorString. [optional]
 */
@property(nonatomic) NSString* anchorYOffset;

@property(nonatomic) DSESPropertyMetadata* anchorYOffsetMetadata;
/* When set to **true**, the information in the tab is bold. [optional]
 */
@property(nonatomic) NSString* bold;

@property(nonatomic) DSESPropertyMetadata* boldMetadata;

@property(nonatomic) DSESErrorDetails* errorDetails;
/* The font to be used for the tab value. Supported Fonts: Arial, Arial, ArialNarrow, Calibri, CourierNew, Garamond, Georgia, Helvetica,   LucidaConsole, Tahoma, TimesNewRoman, Trebuchet, Verdana, MSGothic, MSMincho, Default. [optional]
 */
@property(nonatomic) NSString* font;
/* The font color used for the information in the tab.  Possible values are: Black, BrightBlue, BrightRed, DarkGreen, DarkRed, Gold, Green, NavyBlue, Purple, or White. [optional]
 */
@property(nonatomic) NSString* fontColor;

@property(nonatomic) DSESPropertyMetadata* fontColorMetadata;

@property(nonatomic) DSESPropertyMetadata* fontMetadata;
/* The font size used for the information in the tab.  Possible values are: Size7, Size8, Size9, Size10, Size11, Size12, Size14, Size16, Size18, Size20, Size22, Size24, Size26, Size28, Size36, Size48, or Size72. [optional]
 */
@property(nonatomic) NSString* fontSize;

@property(nonatomic) DSESPropertyMetadata* fontSizeMetadata;
/* When set to **true**, the information in the tab is italic. [optional]
 */
@property(nonatomic) NSString* italic;

@property(nonatomic) DSESPropertyMetadata* italicMetadata;
/* When set to **true**, the signer cannot change the data of the custom tab. [optional]
 */
@property(nonatomic) NSString* locked;

@property(nonatomic) DSESPropertyMetadata* lockedMetadata;
/* Specifies the page number on which the tab is located. [optional]
 */
@property(nonatomic) NSString* pageNumber;

@property(nonatomic) DSESPropertyMetadata* pageNumberMetadata;
/* When set to **true**, the signer is required to fill out this tab [optional]
 */
@property(nonatomic) NSString* required;

@property(nonatomic) DSESPropertyMetadata* requiredMetadata;
/* When set to **true**, the radio button is selected. [optional]
 */
@property(nonatomic) NSString* selected;

@property(nonatomic) DSESPropertyMetadata* selectedMetadata;
/* Indicates the envelope status. Valid values are:  * sent - The envelope is sent to the recipients.  * created - The envelope is saved as a draft and can be modified and sent later. [optional]
 */
@property(nonatomic) NSString* status;

@property(nonatomic) DSESPropertyMetadata* statusMetadata;
/* The unique identifier for the tab. The tabid can be retrieved with the [ML:GET call].      [optional]
 */
@property(nonatomic) NSString* tabId;

@property(nonatomic) DSESPropertyMetadata* tabIdMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* tabOrder;

@property(nonatomic) DSESPropertyMetadata* tabOrderMetadata;
/* When set to **true**, the information in the tab is underlined. [optional]
 */
@property(nonatomic) NSString* underline;

@property(nonatomic) DSESPropertyMetadata* underlineMetadata;
/* Specifies the value of the tab.  [optional]
 */
@property(nonatomic) NSString* value;

@property(nonatomic) DSESPropertyMetadata* valueMetadata;
/* This indicates the horizontal offset of the object on the page. DocuSign uses 72 DPI when determining position. [optional]
 */
@property(nonatomic) NSString* xPosition;

@property(nonatomic) DSESPropertyMetadata* xPositionMetadata;
/* This indicates the vertical offset of the object on the page. DocuSign uses 72 DPI when determining position. [optional]
 */
@property(nonatomic) NSString* yPosition;

@property(nonatomic) DSESPropertyMetadata* yPositionMetadata;

@end
