#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol DSESCommentPublish
@end

@interface DSESCommentPublish : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* _id;
/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* mentions;
/*  [optional]
 */
@property(nonatomic) NSString* text;
/*  [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* threadAnchorKeys;
/*  [optional]
 */
@property(nonatomic) NSString* threadId;
/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* visibleTo;

@end
