#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol DSESEnvelopeIdsRequest
@end

@interface DSESEnvelopeIdsRequest : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* envelopeIds;
/*  A list of transaction Id's used to determining the status of envelopes sent asynchronously. See **transactionId** property on envelopes. [optional]
 */
@property(nonatomic) NSArray<NSString*>* transactionIds;

@end
