#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESSmartSectionCollapsibleDisplaySettings.h>
@protocol DSESSmartSectionCollapsibleDisplaySettings;
@class DSESSmartSectionCollapsibleDisplaySettings;



@protocol DSESSmartSectionDisplaySettings
@end

@interface DSESSmartSectionDisplaySettings : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* cellStyle;

@property(nonatomic) DSESSmartSectionCollapsibleDisplaySettings* collapsibleSettings;
/*  [optional]
 */
@property(nonatomic) NSString* display;
/*  [optional]
 */
@property(nonatomic) NSString* displayLabel;
/*  [optional]
 */
@property(nonatomic) NSNumber* displayOrder;
/*  [optional]
 */
@property(nonatomic) NSNumber* displayPageNumber;
/*  [optional]
 */
@property(nonatomic) NSNumber* hideLabelWhenOpened;
/*  [optional]
 */
@property(nonatomic) NSString* inlineOuterStyle;
/*  [optional]
 */
@property(nonatomic) NSString* labelWhenOpened;
/*  [optional]
 */
@property(nonatomic) NSString* preLabel;
/*  [optional]
 */
@property(nonatomic) NSNumber* scrollToTopWhenOpened;
/*  [optional]
 */
@property(nonatomic) NSString* tableStyle;

@end
