#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESApprove.h>
#import <DSESCheckbox.h>
#import <DSESCommentThread.h>
#import <DSESCompany.h>
#import <DSESDate.h>
#import <DSESDateSigned.h>
#import <DSESDecline.h>
#import <DSESDraw.h>
#import <DSESEmail.h>
#import <DSESEmailAddress.h>
#import <DSESEnvelopeId.h>
#import <DSESFirstName.h>
#import <DSESFormulaTab.h>
#import <DSESFullName.h>
#import <DSESInitialHere.h>
#import <DSESLastName.h>
#import <DSESList.h>
#import <DSESNotarize.h>
#import <DSESNotaryCertificate.h>
#import <DSESNotarySeal.h>
#import <DSESNote.h>
#import <DSESNumber.h>
#import <DSESPolyLineOverlay.h>
#import <DSESRadioGroup.h>
#import <DSESSignHere.h>
#import <DSESSignerAttachment.h>
#import <DSESSmartSection.h>
#import <DSESSsn.h>
#import <DSESTabGroup.h>
#import <DSESText.h>
#import <DSESTitle.h>
#import <DSESView.h>
#import <DSESZip.h>
@protocol DSESApprove;
@class DSESApprove;
@protocol DSESCheckbox;
@class DSESCheckbox;
@protocol DSESCommentThread;
@class DSESCommentThread;
@protocol DSESCompany;
@class DSESCompany;
@protocol DSESDate;
@class DSESDate;
@protocol DSESDateSigned;
@class DSESDateSigned;
@protocol DSESDecline;
@class DSESDecline;
@protocol DSESDraw;
@class DSESDraw;
@protocol DSESEmail;
@class DSESEmail;
@protocol DSESEmailAddress;
@class DSESEmailAddress;
@protocol DSESEnvelopeId;
@class DSESEnvelopeId;
@protocol DSESFirstName;
@class DSESFirstName;
@protocol DSESFormulaTab;
@class DSESFormulaTab;
@protocol DSESFullName;
@class DSESFullName;
@protocol DSESInitialHere;
@class DSESInitialHere;
@protocol DSESLastName;
@class DSESLastName;
@protocol DSESList;
@class DSESList;
@protocol DSESNotarize;
@class DSESNotarize;
@protocol DSESNotaryCertificate;
@class DSESNotaryCertificate;
@protocol DSESNotarySeal;
@class DSESNotarySeal;
@protocol DSESNote;
@class DSESNote;
@protocol DSESNumber;
@class DSESNumber;
@protocol DSESPolyLineOverlay;
@class DSESPolyLineOverlay;
@protocol DSESRadioGroup;
@class DSESRadioGroup;
@protocol DSESSignHere;
@class DSESSignHere;
@protocol DSESSignerAttachment;
@class DSESSignerAttachment;
@protocol DSESSmartSection;
@class DSESSmartSection;
@protocol DSESSsn;
@class DSESSsn;
@protocol DSESTabGroup;
@class DSESTabGroup;
@protocol DSESText;
@class DSESText;
@protocol DSESTitle;
@class DSESTitle;
@protocol DSESView;
@class DSESView;
@protocol DSESZip;
@class DSESZip;



@protocol DSESTabs
@end

@interface DSESTabs : DSESObject

/* Specifies a tag on the document where you want the recipient to approve documents in an envelope without placing a signature or initials on the document. If the recipient clicks the Approve tag during the signing process, the recipient is considered to have signed the document. No information is shown on the document for the approval, but it is recorded as a signature in the envelope history. [optional]
 */
@property(nonatomic) NSArray<DSESApprove>* approveTabs;
/* Specifies a tag on the document in a location where the recipient can select an option. [optional]
 */
@property(nonatomic) NSArray<DSESCheckbox>* checkboxTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESCommentThread>* commentThreadTabs;
/* Specifies a tag on the document where you want the recipient's company name to appear.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response. [optional]
 */
@property(nonatomic) NSArray<DSESCompany>* companyTabs;
/* Specifies a tab on the document where the date the document was signed will automatically appear. [optional]
 */
@property(nonatomic) NSArray<DSESDateSigned>* dateSignedTabs;
/* Specifies a tab on the document where you want the recipient to enter a date. Date tabs are single-line fields that allow date information to be entered in any format. The tooltip for this tab recommends entering the date as MM/DD/YYYY, but this is not enforced. The format entered by the signer is retained.   If you need a particular date format enforced, DocuSign recommends using a Text tab with a Validation Pattern and Validation Message to enforce the format. [optional]
 */
@property(nonatomic) NSArray<DSESDate>* dateTabs;
/* Specifies a tag on the document where you want to give the recipient the option of declining an envelope. If the recipient clicks the Decline tag during the signing process, the envelope is voided. [optional]
 */
@property(nonatomic) NSArray<DSESDecline>* declineTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESDraw>* drawTabs;
/* Specifies a location on the document where you want where you want the recipient's email, as entered in the recipient information, to display. [optional]
 */
@property(nonatomic) NSArray<DSESEmailAddress>* emailAddressTabs;
/* Specifies a tag on the document where you want the recipient to enter an email. Email tags are single-line fields that accept any characters. The system checks that a valid email format (i.e. xxx@yyy.zzz) is entered in the tag. It uses the same parameters as a Text tab, with the validation message and pattern set for email information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response. [optional]
 */
@property(nonatomic) NSArray<DSESEmail>* emailTabs;
/* Specifies a tag on the document where you want the envelope ID for to appear. Recipients cannot enter or change the information in this tab, it is for informational purposes only. [optional]
 */
@property(nonatomic) NSArray<DSESEnvelopeId>* envelopeIdTabs;
/* Specifies tag on a document where you want the recipient's first name to appear. This tag takes the recipient's name, as entered in the recipient information, splits it into sections based on spaces and uses the first section as the first name. [optional]
 */
@property(nonatomic) NSArray<DSESFirstName>* firstNameTabs;
/* Specifies a tag that is used to add a calculated field to a document. Envelope recipients cannot directly enter information into the tag; the formula tab calculates and displays a new value when changes are made to the reference tag values. The reference tag information and calculation operations are entered in the \"formula\" element. See the [ML:Using the Calculated Fields Feature] quick start guide or [ML:DocuSign Service User Guide] for more information about formulas. [optional]
 */
@property(nonatomic) NSArray<DSESFormulaTab>* formulaTabs;
/* Specifies a tag on the document where you want the recipient's name to appear. [optional]
 */
@property(nonatomic) NSArray<DSESFullName>* fullNameTabs;
/* Specifies a tag location in the document at which a recipient will place their initials. The `optional` parameter specifies whether the initials are required or optional. [optional]
 */
@property(nonatomic) NSArray<DSESInitialHere>* initialHereTabs;
/* Specifies a tag on a document where you want the recipient's last name to appear. This tag takes the recipient's name, as entered in the recipient information, splits it into sections based on spaces and uses the last section as the last name. [optional]
 */
@property(nonatomic) NSArray<DSESLastName>* lastNameTabs;
/* Specify this tag to give your recipient a list of options, presented as a drop-down list, from which they can select. [optional]
 */
@property(nonatomic) NSArray<DSESList>* listTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESNotarize>* notarizeTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESNotaryCertificate>* notaryCertificateTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESNotarySeal>* notarySealTabs;
/* Specifies a location on the document where you want to place additional information, in the form of a note, for a recipient. [optional]
 */
@property(nonatomic) NSArray<DSESNote>* noteTabs;
/* Specifies a tag on the document where you want the recipient to enter a number. It uses the same parameters as a Text tab, with the validation message and pattern set for number information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response.  [optional]
 */
@property(nonatomic) NSArray<DSESNumber>* numberTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESPolyLineOverlay>* polyLineOverlayTabs;
/* Specifies a tag on the document in a location where the recipient can select one option from a group of options using a radio button. The radio buttons do not have to be on the same page in a document. [optional]
 */
@property(nonatomic) NSArray<DSESRadioGroup>* radioGroupTabs;
/* Specifies a tag on the document when you want the recipient to add supporting documents to an envelope. [optional]
 */
@property(nonatomic) NSArray<DSESSignerAttachment>* signerAttachmentTabs;
/* A complex type the contains information about the tag that specifies where the recipient places their signature in the document. The \"optional\" parameter sets if the signature is required or optional.  [optional]
 */
@property(nonatomic) NSArray<DSESSignHere>* signHereTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESSmartSection>* smartSectionTabs;
/* Specifies a tag on the document where you want the recipient to enter a Social Security Number (SSN). A SSN can be typed with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for SSN information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response. [optional]
 */
@property(nonatomic) NSArray<DSESSsn>* ssnTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESTabGroup>* tabGroups;
/* Specifies a that that is an adaptable field that allows the recipient to enter different text information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response. [optional]
 */
@property(nonatomic) NSArray<DSESText>* textTabs;
/* Specifies a tag on the document where you want the recipient's title to appear.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response. [optional]
 */
@property(nonatomic) NSArray<DSESTitle>* titleTabs;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESView>* viewTabs;
/* Specifies a tag on the document where you want the recipient to enter a ZIP code. The ZIP code can be a five numbers or the ZIP+4 format with nine numbers. The zip code can be typed with or without dashes. It uses the same parameters as a Text tab, with the validation message and pattern set for ZIP code information.  When getting information that includes this tab type, the original value of the tab when the associated envelope was sent is included in the response. [optional]
 */
@property(nonatomic) NSArray<DSESZip>* zipTabs;

@end
