#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESFormDataItem.h>
@protocol DSESFormDataItem;
@class DSESFormDataItem;



@protocol DSESRecipientFormData
@end

@interface DSESRecipientFormData : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* declinedTime;
/*  [optional]
 */
@property(nonatomic) NSString* deliveredTime;
/*  [optional]
 */
@property(nonatomic) NSString* email;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESFormDataItem>* formData;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/* Unique for the recipient. It is used by the tab element to indicate which recipient is to sign the Document. [optional]
 */
@property(nonatomic) NSString* recipientId;
/*  [optional]
 */
@property(nonatomic) NSString* sentTime;
/*  [optional]
 */
@property(nonatomic) NSString* signedTime;

@end
