#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESSettingsMetadata.h>
@protocol DSESSettingsMetadata;
@class DSESSettingsMetadata;



@protocol DSESUserAccountManagementGranularInformation
@end

@interface DSESUserAccountManagementGranularInformation : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* canManageAccountSecuritySettings;

@property(nonatomic) DSESSettingsMetadata* canManageAccountSecuritySettingsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canManageAccountSettings;

@property(nonatomic) DSESSettingsMetadata* canManageAccountSettingsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canManageAdmins;

@property(nonatomic) DSESSettingsMetadata* canManageAdminsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canManageEnvelopeTransfer;

@property(nonatomic) DSESSettingsMetadata* canManageEnvelopeTransferMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canManageReporting;

@property(nonatomic) DSESSettingsMetadata* canManageReportingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canManageSharing;

@property(nonatomic) DSESSettingsMetadata* canManageSharingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canManageSigningGroups;

@property(nonatomic) DSESSettingsMetadata* canManageSigningGroupsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canManageUsers;

@property(nonatomic) DSESSettingsMetadata* canManageUsersMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canViewUsers;

@end
