#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESErrorDetails.h>
#import <DSESTemplateMatch.h>
@protocol DSESErrorDetails;
@class DSESErrorDetails;
@protocol DSESTemplateMatch;
@class DSESTemplateMatch;



@protocol DSESTemplateSummary
@end

@interface DSESTemplateSummary : DSESObject

/* Reserved: TBD [optional]
 */
@property(nonatomic) NSString* applied;
/* Specifies the document ID number that the tab is placed on. This must refer to an existing Document's ID attribute. [optional]
 */
@property(nonatomic) NSString* documentId;
/*  [optional]
 */
@property(nonatomic) NSString* documentName;

@property(nonatomic) DSESErrorDetails* errorDetails;
/*  [optional]
 */
@property(nonatomic) NSString* name;
/* The unique identifier of the template. If this is not provided, DocuSign will generate a value.  [optional]
 */
@property(nonatomic) NSString* templateId;

@property(nonatomic) DSESTemplateMatch* templateMatch;
/*  [optional]
 */
@property(nonatomic) NSString* uri;

@end
