#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESAccessCodeFormat.h>
#import <DSESAccountIdentityVerificationWorkflow.h>
#import <DSESAccountNotification.h>
#import <DSESAccountUISettings.h>
#import <DSESAddressInformation.h>
#import <DSESExternalDocumentSources.h>
#import <DSESIdCheckConfiguration.h>
#import <DSESSettingsMetadata.h>
#import <DSESTabAccountSettings.h>
@protocol DSESAccessCodeFormat;
@class DSESAccessCodeFormat;
@protocol DSESAccountIdentityVerificationWorkflow;
@class DSESAccountIdentityVerificationWorkflow;
@protocol DSESAccountNotification;
@class DSESAccountNotification;
@protocol DSESAccountUISettings;
@class DSESAccountUISettings;
@protocol DSESAddressInformation;
@class DSESAddressInformation;
@protocol DSESExternalDocumentSources;
@class DSESExternalDocumentSources;
@protocol DSESIdCheckConfiguration;
@class DSESIdCheckConfiguration;
@protocol DSESSettingsMetadata;
@class DSESSettingsMetadata;
@protocol DSESTabAccountSettings;
@class DSESTabAccountSettings;



@protocol DSESAccountSettingsInformation
@end

@interface DSESAccountSettingsInformation : DSESObject


@property(nonatomic) DSESAccessCodeFormat* accessCodeFormat;
/*  [optional]
 */
@property(nonatomic) NSString* accountDateTimeFormat;

@property(nonatomic) DSESSettingsMetadata* accountDateTimeFormatMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* accountDefaultLanguage;

@property(nonatomic) DSESSettingsMetadata* accountDefaultLanguageMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* accountName;

@property(nonatomic) DSESSettingsMetadata* accountNameMetadata;

@property(nonatomic) DSESAccountNotification* accountNotification;

@property(nonatomic) DSESAccountUISettings* accountUISettings;
/*  [optional]
 */
@property(nonatomic) NSString* adoptSigConfig;

@property(nonatomic) DSESSettingsMetadata* adoptSigConfigMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* advancedCorrect;

@property(nonatomic) DSESSettingsMetadata* advancedCorrectMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAccessCodeFormat;

@property(nonatomic) DSESSettingsMetadata* allowAccessCodeFormatMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAccountManagementGranular;

@property(nonatomic) DSESSettingsMetadata* allowAccountManagementGranularMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAccountMemberNameChange;

@property(nonatomic) DSESSettingsMetadata* allowAccountMemberNameChangeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAdvancedRecipientRoutingConditional;

@property(nonatomic) DSESSettingsMetadata* allowAdvancedRecipientRoutingConditionalMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAgentNameEmailEdit;

@property(nonatomic) DSESSettingsMetadata* allowAgentNameEmailEditMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAgreementActions;

@property(nonatomic) DSESSettingsMetadata* allowAgreementActionsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAutoNavSettings;

@property(nonatomic) DSESSettingsMetadata* allowAutoNavSettingsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowAutoTagging;

@property(nonatomic) DSESSettingsMetadata* allowAutoTaggingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowBulkSend;

@property(nonatomic) DSESSettingsMetadata* allowBulkSendMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowCDWithdraw;

@property(nonatomic) DSESSettingsMetadata* allowCDWithdrawMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowConnectHttpListenerConfigs;
/*  [optional]
 */
@property(nonatomic) NSString* allowConnectSendFinishLater;

@property(nonatomic) DSESSettingsMetadata* allowConnectSendFinishLaterMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowConnectUnifiedPayloadUI;
/*  [optional]
 */
@property(nonatomic) NSString* allowConsumerDisclosureOverride;

@property(nonatomic) DSESSettingsMetadata* allowConsumerDisclosureOverrideMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowDataDownload;

@property(nonatomic) DSESSettingsMetadata* allowDataDownloadMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowDocumentDisclosures;

@property(nonatomic) DSESSettingsMetadata* allowDocumentDisclosuresMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowDocumentsOnSignedEnvelopes;

@property(nonatomic) DSESSettingsMetadata* allowDocumentsOnSignedEnvelopesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowDocumentVisibility;

@property(nonatomic) DSESSettingsMetadata* allowDocumentVisibilityMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowEHankoStamps;

@property(nonatomic) DSESSettingsMetadata* allowEHankoStampsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowENoteEOriginal;

@property(nonatomic) DSESSettingsMetadata* allowENoteEOriginalMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowEnvelopeCorrect;

@property(nonatomic) DSESSettingsMetadata* allowEnvelopeCorrectMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowEnvelopeCustodyTransfer;

@property(nonatomic) DSESSettingsMetadata* allowEnvelopeCustodyTransferMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowEnvelopeCustomFields;

@property(nonatomic) DSESSettingsMetadata* allowEnvelopeCustomFieldsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowEnvelopePublishReporting;

@property(nonatomic) DSESSettingsMetadata* allowEnvelopePublishReportingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowEnvelopeReporting;

@property(nonatomic) DSESSettingsMetadata* allowEnvelopeReportingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowExpression;

@property(nonatomic) DSESSettingsMetadata* allowExpressionMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowExpressSignerCertificate;

@property(nonatomic) DSESSettingsMetadata* allowExpressSignerCertificateMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowExtendedSendingResourceFile;

@property(nonatomic) DSESSettingsMetadata* allowExtendedSendingResourceFileMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowExternalSignaturePad;

@property(nonatomic) DSESSettingsMetadata* allowExternalSignaturePadMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowIDVLevel1;

@property(nonatomic) DSESSettingsMetadata* allowIDVLevel1Metadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowIDVPlatform;

@property(nonatomic) DSESSettingsMetadata* allowIDVPlatformMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowInPerson;

@property(nonatomic) DSESSettingsMetadata* allowInPersonMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowManagedStamps;

@property(nonatomic) DSESSettingsMetadata* allowManagedStampsMetadata;
/* When set to **true**, Document Markup is enabled for envelope. Account must have Document Markup enabled to use this [optional]
 */
@property(nonatomic) NSString* allowMarkup;

@property(nonatomic) DSESSettingsMetadata* allowMarkupMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowMemberTimeZone;

@property(nonatomic) DSESSettingsMetadata* allowMemberTimeZoneMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowMergeFields;

@property(nonatomic) DSESSettingsMetadata* allowMergeFieldsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowMultipleBrandProfiles;

@property(nonatomic) DSESSettingsMetadata* allowMultipleBrandProfilesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowMultipleSignerAttachments;

@property(nonatomic) DSESSettingsMetadata* allowMultipleSignerAttachmentsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowNonUSPhoneAuth;

@property(nonatomic) DSESSettingsMetadata* allowNonUSPhoneAuthMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowOcrOfEnvelopeDocuments;

@property(nonatomic) DSESSettingsMetadata* allowOcrOfEnvelopeDocumentsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowOfflineSigning;

@property(nonatomic) DSESSettingsMetadata* allowOfflineSigningMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowOpenTrustSignerCertificate;

@property(nonatomic) DSESSettingsMetadata* allowOpenTrustSignerCertificateMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowOrganizations;

@property(nonatomic) DSESSettingsMetadata* allowOrganizationsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowPaymentProcessing;

@property(nonatomic) DSESSettingsMetadata* allowPaymentProcessingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowPersonalSignerCertificate;

@property(nonatomic) DSESSettingsMetadata* allowPersonalSignerCertificateMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowPhoneAuthentication;

@property(nonatomic) DSESSettingsMetadata* allowPhoneAuthenticationMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowPhoneAuthOverride;

@property(nonatomic) DSESSettingsMetadata* allowPhoneAuthOverrideMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowPrivateSigningGroups;

@property(nonatomic) DSESSettingsMetadata* allowPrivateSigningGroupsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowReminders;

@property(nonatomic) DSESSettingsMetadata* allowRemindersMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowResourceFileBranding;

@property(nonatomic) DSESSettingsMetadata* allowResourceFileBrandingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSafeBioPharmaSignerCertificate;

@property(nonatomic) DSESSettingsMetadata* allowSafeBioPharmaSignerCertificateMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSecurityAppliance;

@property(nonatomic) DSESSettingsMetadata* allowSecurityApplianceMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSendToCertifiedDelivery;

@property(nonatomic) DSESSettingsMetadata* allowSendToCertifiedDeliveryMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSendToIntermediary;

@property(nonatomic) DSESSettingsMetadata* allowSendToIntermediaryMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowServerTemplates;

@property(nonatomic) DSESSettingsMetadata* allowServerTemplatesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSetEmbeddedRecipientStartURL;

@property(nonatomic) DSESSettingsMetadata* allowSetEmbeddedRecipientStartURLMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSharedTabs;

@property(nonatomic) DSESSettingsMetadata* allowSharedTabsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSignatureStamps;

@property(nonatomic) DSESSettingsMetadata* allowSignatureStampsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSignDocumentFromHomePage;

@property(nonatomic) DSESSettingsMetadata* allowSignDocumentFromHomePageMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSignerReassign;

@property(nonatomic) DSESSettingsMetadata* allowSignerReassignMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSignerReassignOverride;

@property(nonatomic) DSESSettingsMetadata* allowSignerReassignOverrideMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSigningExtensions;

@property(nonatomic) DSESSettingsMetadata* allowSigningExtensionsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSigningGroups;

@property(nonatomic) DSESSettingsMetadata* allowSigningGroupsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSigningRadioDeselect;

@property(nonatomic) DSESSettingsMetadata* allowSigningRadioDeselectMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSignNow;
/*  [optional]
 */
@property(nonatomic) NSString* allowSignNowMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSMSDelivery;

@property(nonatomic) DSESSettingsMetadata* allowSMSDeliveryMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSocialIdLogin;

@property(nonatomic) DSESSettingsMetadata* allowSocialIdLoginMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowSupplementalDocuments;

@property(nonatomic) DSESSettingsMetadata* allowSupplementalDocumentsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowUsersToAccessDirectory;

@property(nonatomic) DSESSettingsMetadata* allowUsersToAccessDirectoryMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* allowValueInsights;

@property(nonatomic) DSESSettingsMetadata* allowValueInsightsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* anchorPopulationScope;

@property(nonatomic) DSESSettingsMetadata* anchorPopulationScopeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* anchorTagVersionedPlacementEnabled;

@property(nonatomic) DSESSettingsMetadata* anchorTagVersionedPlacementMetadataEnabled;
/*  [optional]
 */
@property(nonatomic) NSString* attachCompletedEnvelope;

@property(nonatomic) DSESSettingsMetadata* attachCompletedEnvelopeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* authenticationCheck;

@property(nonatomic) DSESSettingsMetadata* authenticationCheckMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* autoNavRule;

@property(nonatomic) DSESSettingsMetadata* autoNavRuleMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* autoProvisionSignerAccount;

@property(nonatomic) DSESSettingsMetadata* autoProvisionSignerAccountMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* bccEmailArchive;

@property(nonatomic) DSESSettingsMetadata* bccEmailArchiveMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* betaSwitchConfiguration;

@property(nonatomic) DSESSettingsMetadata* betaSwitchConfigurationMetadata;

@property(nonatomic) DSESAddressInformation* billingAddress;

@property(nonatomic) DSESSettingsMetadata* billingAddressMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* bulkSend;
/*  [optional]
 */
@property(nonatomic) NSString* bulkSendMaxCopiesInBatch;
/*  [optional]
 */
@property(nonatomic) NSString* bulkSendMaxUnprocessedEnvelopesCount;

@property(nonatomic) DSESSettingsMetadata* bulkSendMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canSelfBrandSend;

@property(nonatomic) DSESSettingsMetadata* canSelfBrandSendMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canSelfBrandSign;

@property(nonatomic) DSESSettingsMetadata* canSelfBrandSignMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* canUseSalesforceOAuth;

@property(nonatomic) DSESSettingsMetadata* canUseSalesforceOAuthMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* captureVoiceRecording;

@property(nonatomic) DSESSettingsMetadata* captureVoiceRecordingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* cfrUseWideImage;

@property(nonatomic) DSESSettingsMetadata* cfrUseWideImageMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* checkForMultipleAdminsOnAccount;

@property(nonatomic) DSESSettingsMetadata* checkForMultipleAdminsOnAccountMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* chromeSignatureEnabled;

@property(nonatomic) DSESSettingsMetadata* chromeSignatureEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* commentEmailShowMessageText;

@property(nonatomic) DSESSettingsMetadata* commentEmailShowMessageTextMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* commentsAllowEnvelopeOverride;

@property(nonatomic) DSESSettingsMetadata* commentsAllowEnvelopeOverrideMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* conditionalFieldsEnabled;

@property(nonatomic) DSESSettingsMetadata* conditionalFieldsEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* consumerDisclosureFrequency;

@property(nonatomic) DSESSettingsMetadata* consumerDisclosureFrequencyMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* convertPdfFields;

@property(nonatomic) DSESSettingsMetadata* convertPdfFieldsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* dataPopulationScope;

@property(nonatomic) DSESSettingsMetadata* dataPopulationScopeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableMobileApp;

@property(nonatomic) DSESSettingsMetadata* disableMobileAppMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableMobilePushNotifications;

@property(nonatomic) DSESSettingsMetadata* disableMobilePushNotificationsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableMobileSending;

@property(nonatomic) DSESSettingsMetadata* disableMobileSendingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableMultipleSessions;

@property(nonatomic) DSESSettingsMetadata* disableMultipleSessionsMetadata;

@property(nonatomic) DSESSettingsMetadata* disablePurgeNotificationsForSenderMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableSignerCertView;

@property(nonatomic) DSESSettingsMetadata* disableSignerCertViewMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableSignerHistoryView;

@property(nonatomic) DSESSettingsMetadata* disableSignerHistoryViewMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableStyleSignature;

@property(nonatomic) DSESSettingsMetadata* disableStyleSignatureMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableUploadSignature;

@property(nonatomic) DSESSettingsMetadata* disableUploadSignatureMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* disableUserSharing;

@property(nonatomic) DSESSettingsMetadata* disableUserSharingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* displayBetaSwitch;

@property(nonatomic) DSESSettingsMetadata* displayBetaSwitchMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* documentConversionRestrictions;

@property(nonatomic) DSESSettingsMetadata* documentConversionRestrictionsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* documentRetention;

@property(nonatomic) DSESSettingsMetadata* documentRetentionMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* documentRetentionPurgeTabs;
/*  [optional]
 */
@property(nonatomic) NSString* documentVisibility;

@property(nonatomic) DSESSettingsMetadata* documentVisibilityMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* emailTemplateVersion;

@property(nonatomic) DSESSettingsMetadata* emailTemplateVersionMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableAccessCodeGenerator;

@property(nonatomic) DSESSettingsMetadata* enableAccessCodeGeneratorMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableAdvancedPayments;

@property(nonatomic) DSESSettingsMetadata* enableAdvancedPaymentsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableAdvancedPowerForms;

@property(nonatomic) DSESSettingsMetadata* enableAdvancedPowerFormsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableAutoNav;

@property(nonatomic) DSESSettingsMetadata* enableAutoNavMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableCalculatedFields;

@property(nonatomic) DSESSettingsMetadata* enableCalculatedFieldsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableClickwraps;

@property(nonatomic) DSESSettingsMetadata* enableClickwrapsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableCommentsHistoryDownloadInSigning;

@property(nonatomic) DSESSettingsMetadata* enableCommentsHistoryDownloadInSigningMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableCustomerSatisfactionMetricTracking;

@property(nonatomic) DSESSettingsMetadata* enableCustomerSatisfactionMetricTrackingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableDSPro;

@property(nonatomic) DSESSettingsMetadata* enableDSProMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableEnvelopeStampingByAccountAdmin;

@property(nonatomic) DSESSettingsMetadata* enableEnvelopeStampingByAccountAdminMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableEnvelopeStampingByDSAdmin;

@property(nonatomic) DSESSettingsMetadata* enableEnvelopeStampingByDSAdminMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableInBrowserEditor;

@property(nonatomic) DSESSettingsMetadata* enableInBrowserEditorMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enablePaymentProcessing;

@property(nonatomic) DSESSettingsMetadata* enablePaymentProcessingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enablePowerForm;
/*  [optional]
 */
@property(nonatomic) NSString* enablePowerFormDirect;

@property(nonatomic) DSESSettingsMetadata* enablePowerFormDirectMetadata;

@property(nonatomic) DSESSettingsMetadata* enablePowerFormMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableRecipientDomainValidation;

@property(nonatomic) DSESSettingsMetadata* enableRecipientDomainValidationMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableReportLinks;

@property(nonatomic) DSESSettingsMetadata* enableReportLinksMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableRequireSignOnPaper;

@property(nonatomic) DSESSettingsMetadata* enableRequireSignOnPaperMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableReservedDomain;

@property(nonatomic) DSESSettingsMetadata* enableReservedDomainMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableResponsiveSigning;

@property(nonatomic) DSESSettingsMetadata* enableResponsiveSigningMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableScheduledRelease;

@property(nonatomic) DSESSettingsMetadata* enableScheduledReleaseMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSearchUI;

@property(nonatomic) DSESSettingsMetadata* enableSearchUIMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSendingTagsFontSettings;

@property(nonatomic) DSESSettingsMetadata* enableSendingTagsFontSettingsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSendToAgent;

@property(nonatomic) DSESSettingsMetadata* enableSendToAgentMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSendToIntermediary;

@property(nonatomic) DSESSettingsMetadata* enableSendToIntermediaryMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSendToManage;

@property(nonatomic) DSESSettingsMetadata* enableSendToManageMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSequentialSigningAPI;

@property(nonatomic) DSESSettingsMetadata* enableSequentialSigningAPIMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSequentialSigningUI;

@property(nonatomic) DSESSettingsMetadata* enableSequentialSigningUIMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSignerAttachments;

@property(nonatomic) DSESSettingsMetadata* enableSignerAttachmentsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSigningExtensionComments;

@property(nonatomic) DSESSettingsMetadata* enableSigningExtensionCommentsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSigningExtensionConversations;

@property(nonatomic) DSESSettingsMetadata* enableSigningExtensionConversationsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSigningOrderSettingsForAccount;

@property(nonatomic) DSESSettingsMetadata* enableSigningOrderSettingsForAccountMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSignOnPaper;

@property(nonatomic) DSESSettingsMetadata* enableSignOnPaperMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSignOnPaperOverride;

@property(nonatomic) DSESSettingsMetadata* enableSignOnPaperOverrideMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSignWithNotary;

@property(nonatomic) DSESSettingsMetadata* enableSignWithNotaryMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSmartContracts;

@property(nonatomic) DSESSettingsMetadata* enableSmartContractsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSMSAuthentication;

@property(nonatomic) DSESSettingsMetadata* enableSMSAuthenticationMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableSocialIdLogin;

@property(nonatomic) DSESSettingsMetadata* enableSocialIdLoginMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableStrikeThrough;

@property(nonatomic) DSESSettingsMetadata* enableStrikeThroughMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableTransactionPoint;

@property(nonatomic) DSESSettingsMetadata* enableTransactionPointMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableVaulting;

@property(nonatomic) DSESSettingsMetadata* enableVaultingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableWitnessing;

@property(nonatomic) DSESSettingsMetadata* enableWitnessingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enforceTemplateNameUniqueness;

@property(nonatomic) DSESSettingsMetadata* enforceTemplateNameUniquenessMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeIntegrationAllowed;

@property(nonatomic) DSESSettingsMetadata* envelopeIntegrationAllowedMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeIntegrationEnabled;

@property(nonatomic) DSESSettingsMetadata* envelopeIntegrationEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* envelopeStampingDefaultValue;

@property(nonatomic) DSESSettingsMetadata* envelopeStampingDefaultValueMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* expressSend;
/*  [optional]
 */
@property(nonatomic) NSString* expressSendAllowTabs;

@property(nonatomic) DSESSettingsMetadata* expressSendAllowTabsMetadata;

@property(nonatomic) DSESSettingsMetadata* expressSendMetadata;

@property(nonatomic) DSESExternalDocumentSources* externalDocumentSources;
/*  [optional]
 */
@property(nonatomic) NSString* externalSignaturePadType;

@property(nonatomic) DSESSettingsMetadata* externalSignaturePadTypeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* faxOutEnabled;

@property(nonatomic) DSESSettingsMetadata* faxOutEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* guidedFormsHtmlAllowed;

@property(nonatomic) DSESSettingsMetadata* guidedFormsHtmlAllowedMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* hideAccountAddressInCoC;

@property(nonatomic) DSESSettingsMetadata* hideAccountAddressInCoCMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* hidePricing;

@property(nonatomic) DSESSettingsMetadata* hidePricingMetadata;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESIdCheckConfiguration>* idCheckConfigurations;
/*  [optional]
 */
@property(nonatomic) NSString* idCheckExpire;
/*  [optional]
 */
@property(nonatomic) NSString* idCheckExpireDays;

@property(nonatomic) DSESSettingsMetadata* idCheckExpireDaysMetadata;

@property(nonatomic) DSESSettingsMetadata* idCheckExpireMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* idCheckExpireMinutes;

@property(nonatomic) DSESSettingsMetadata* idCheckExpireMinutesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* idCheckRequired;

@property(nonatomic) DSESSettingsMetadata* idCheckRequiredMetadata;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESAccountIdentityVerificationWorkflow>* identityVerification;

@property(nonatomic) DSESSettingsMetadata* identityVerificationMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* ignoreErrorIfAnchorTabNotFound;

@property(nonatomic) DSESSettingsMetadata* ignoreErrorIfAnchorTabNotFoundMetadataEnabled;
/*  [optional]
 */
@property(nonatomic) NSString* inPersonIDCheckQuestion;

@property(nonatomic) DSESSettingsMetadata* inPersonIDCheckQuestionMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* inPersonSigningEnabled;

@property(nonatomic) DSESSettingsMetadata* inPersonSigningEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* inSessionEnabled;

@property(nonatomic) DSESSettingsMetadata* inSessionEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* inSessionSuppressEmails;

@property(nonatomic) DSESSettingsMetadata* inSessionSuppressEmailsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* maximumSigningGroups;

@property(nonatomic) DSESSettingsMetadata* maximumSigningGroupsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* maximumUsersPerSigningGroup;

@property(nonatomic) DSESSettingsMetadata* maximumUsersPerSigningGroupMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* maxNumberOfCustomStamps;
/*  [optional]
 */
@property(nonatomic) NSString* mobileSessionTimeout;

@property(nonatomic) DSESSettingsMetadata* mobileSessionTimeoutMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* numberOfActiveCustomStamps;
/*  [optional]
 */
@property(nonatomic) NSString* optInMobileSigningV02;

@property(nonatomic) DSESSettingsMetadata* optInMobileSigningV02Metadata;
/*  [optional]
 */
@property(nonatomic) NSString* optOutAutoNavTextAndTabColorUpdates;

@property(nonatomic) DSESSettingsMetadata* optOutAutoNavTextAndTabColorUpdatesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* optOutNewPlatformSeal;

@property(nonatomic) DSESSettingsMetadata* optOutNewPlatformSealPlatformMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* phoneAuthRecipientMayProvidePhoneNumber;

@property(nonatomic) DSESSettingsMetadata* phoneAuthRecipientMayProvidePhoneNumberMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* pkiSignDownloadedPDFDocs;

@property(nonatomic) DSESSettingsMetadata* pkiSignDownloadedPDFDocsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* recipientsCanSignOffline;

@property(nonatomic) DSESSettingsMetadata* recipientsCanSignOfflineMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* recipientSigningAutoNavigationControl;

@property(nonatomic) DSESSettingsMetadata* recipientSigningAutoNavigationControlMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* require21CFRpt11Compliance;

@property(nonatomic) DSESSettingsMetadata* require21CFRpt11ComplianceMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* requireDeclineReason;

@property(nonatomic) DSESSettingsMetadata* requireDeclineReasonMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* requireExternalUserManagement;

@property(nonatomic) DSESSettingsMetadata* requireExternalUserManagementMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* requireSignerCertificateType;

@property(nonatomic) DSESSettingsMetadata* requireSignerCertificateTypeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* rsaVeridAccountName;
/*  [optional]
 */
@property(nonatomic) NSString* rsaVeridPassword;
/*  [optional]
 */
@property(nonatomic) NSString* rsaVeridRuleset;
/*  [optional]
 */
@property(nonatomic) NSString* rsaVeridUserId;
/*  [optional]
 */
@property(nonatomic) NSString* selfSignedRecipientEmailDocument;

@property(nonatomic) DSESSettingsMetadata* selfSignedRecipientEmailDocumentMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* selfSignedRecipientEmailDocumentUserOverride;

@property(nonatomic) DSESSettingsMetadata* selfSignedRecipientEmailDocumentUserOverrideMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* senderCanSignInEachLocation;

@property(nonatomic) DSESSettingsMetadata* senderCanSignInEachLocationMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* senderMustAuthenticateSigning;

@property(nonatomic) DSESSettingsMetadata* senderMustAuthenticateSigningMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* sendingTagsFontColor;

@property(nonatomic) DSESSettingsMetadata* sendingTagsFontColorMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* sendingTagsFontName;

@property(nonatomic) DSESSettingsMetadata* sendingTagsFontNameMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* sendingTagsFontSize;

@property(nonatomic) DSESSettingsMetadata* sendingTagsFontSizeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* sendToCertifiedDeliveryEnabled;

@property(nonatomic) DSESSettingsMetadata* sendToCertifiedDeliveryEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* sessionTimeout;

@property(nonatomic) DSESSettingsMetadata* sessionTimeoutMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* setRecipEmailLang;

@property(nonatomic) DSESSettingsMetadata* setRecipEmailLangMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* setRecipSignLang;

@property(nonatomic) DSESSettingsMetadata* setRecipSignLangMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* sharedTemplateFolders;

@property(nonatomic) DSESSettingsMetadata* sharedTemplateFoldersMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* showCompleteDialogInEmbeddedSession;

@property(nonatomic) DSESSettingsMetadata* showCompleteDialogInEmbeddedSessionMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* showConditionalRoutingOnSend;

@property(nonatomic) DSESSettingsMetadata* showConditionalRoutingOnSendMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* showInitialConditionalFields;

@property(nonatomic) DSESSettingsMetadata* showInitialConditionalFieldsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* showLocalizedWatermarks;

@property(nonatomic) DSESSettingsMetadata* showLocalizedWatermarksMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* showTutorials;

@property(nonatomic) DSESSettingsMetadata* showTutorialsMetadata;
/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* signatureProviders;

@property(nonatomic) DSESSettingsMetadata* signatureProvidersMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signDateFormat;

@property(nonatomic) DSESSettingsMetadata* signDateFormatMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerAttachCertificateToEnvelopePDF;

@property(nonatomic) DSESSettingsMetadata* signerAttachCertificateToEnvelopePDFMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerAttachConcat;

@property(nonatomic) DSESSettingsMetadata* signerAttachConcatMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerCanCreateAccount;

@property(nonatomic) DSESSettingsMetadata* signerCanCreateAccountMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerCanSignOnMobile;

@property(nonatomic) DSESSettingsMetadata* signerCanSignOnMobileMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerInSessionUseEnvelopeCompleteEmail;

@property(nonatomic) DSESSettingsMetadata* signerInSessionUseEnvelopeCompleteEmailMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerLoginRequirements;

@property(nonatomic) DSESSettingsMetadata* signerLoginRequirementsMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerMustHaveAccount;

@property(nonatomic) DSESSettingsMetadata* signerMustHaveAccountMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerMustLoginToSign;

@property(nonatomic) DSESSettingsMetadata* signerMustLoginToSignMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signerShowSecureFieldInitialValues;

@property(nonatomic) DSESSettingsMetadata* signerShowSecureFieldInitialValuesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signingSessionTimeout;

@property(nonatomic) DSESSettingsMetadata* signingSessionTimeoutMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signingUiVersion;

@property(nonatomic) DSESSettingsMetadata* signingUiVersionMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signTimeFormat;

@property(nonatomic) DSESSettingsMetadata* signTimeFormatMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* signTimeShowAmPm;

@property(nonatomic) DSESSettingsMetadata* signTimeShowAmPmMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* simplifiedSendingEnabled;

@property(nonatomic) DSESSettingsMetadata* simplifiedSendingEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* singleSignOnEnabled;

@property(nonatomic) DSESSettingsMetadata* singleSignOnEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* skipAuthCompletedEnvelopes;

@property(nonatomic) DSESSettingsMetadata* skipAuthCompletedEnvelopesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* socialIdRecipAuth;

@property(nonatomic) DSESSettingsMetadata* socialIdRecipAuthMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* specifyDocumentVisibility;

@property(nonatomic) DSESSettingsMetadata* specifyDocumentVisibilityMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* startInAdvancedCorrect;

@property(nonatomic) DSESSettingsMetadata* startInAdvancedCorrectMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* supplementalDocumentsMustAccept;

@property(nonatomic) DSESSettingsMetadata* supplementalDocumentsMustAcceptMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* supplementalDocumentsMustRead;

@property(nonatomic) DSESSettingsMetadata* supplementalDocumentsMustReadMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* supplementalDocumentsMustView;

@property(nonatomic) DSESSettingsMetadata* supplementalDocumentsMustViewMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* suppressCertificateEnforcement;

@property(nonatomic) DSESSettingsMetadata* suppressCertificateEnforcementMetadata;

@property(nonatomic) DSESTabAccountSettings* tabAccountSettings;
/*  [optional]
 */
@property(nonatomic) NSString* timezoneOffsetAPI;

@property(nonatomic) DSESSettingsMetadata* timezoneOffsetAPIMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* timezoneOffsetUI;

@property(nonatomic) DSESSettingsMetadata* timezoneOffsetUIMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* universalSignatureOptIn;
/*  [optional]
 */
@property(nonatomic) NSString* useAccountLevelEmail;

@property(nonatomic) DSESSettingsMetadata* useAccountLevelEmailMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useConsumerDisclosure;

@property(nonatomic) DSESSettingsMetadata* useConsumerDisclosureMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useConsumerDisclosureWithinAccount;

@property(nonatomic) DSESSettingsMetadata* useConsumerDisclosureWithinAccountMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useDerivedKeys;

@property(nonatomic) DSESSettingsMetadata* useDerivedKeysMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useDocuSignExpressSignerCertificate;

@property(nonatomic) DSESSettingsMetadata* useDocuSignExpressSignerCertificateMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useMultiAppGroupsData;

@property(nonatomic) DSESSettingsMetadata* useMultiAppGroupsDataMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useNewBlobForPdf;

@property(nonatomic) DSESSettingsMetadata* useNewBlobForPdfMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useSAFESignerCertificates;

@property(nonatomic) DSESSettingsMetadata* useSAFESignerCertificatesMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* usesAPI;

@property(nonatomic) DSESSettingsMetadata* usesAPIMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* useSignatureProviderPlatform;

@property(nonatomic) DSESSettingsMetadata* useSignatureProviderPlatformMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* validationsAllowed;

@property(nonatomic) DSESSettingsMetadata* validationsAllowedMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* validationsBrand;

@property(nonatomic) DSESSettingsMetadata* validationsBrandMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* validationsCadence;

@property(nonatomic) DSESSettingsMetadata* validationsCadenceMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* validationsEnabled;

@property(nonatomic) DSESSettingsMetadata* validationsEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* validationsReport;

@property(nonatomic) DSESSettingsMetadata* validationsReportMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* waterMarkEnabled;

@property(nonatomic) DSESSettingsMetadata* waterMarkEnabledMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* writeReminderToEnvelopeHistory;

@property(nonatomic) DSESSettingsMetadata* writeReminderToEnvelopeHistoryMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* wurflMinAllowableScreenSize;

@property(nonatomic) DSESSettingsMetadata* wurflMinAllowableScreenSizeMetadata;

@end
