#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESErrorDetails.h>
#import <DSESNameValue.h>
#import <DSESPage.h>
#import <DSESPropertyMetadata.h>
#import <DSESSignatureType.h>
@protocol DSESErrorDetails;
@class DSESErrorDetails;
@protocol DSESNameValue;
@class DSESNameValue;
@protocol DSESPage;
@class DSESPage;
@protocol DSESPropertyMetadata;
@class DSESPropertyMetadata;
@protocol DSESSignatureType;
@class DSESSignatureType;



@protocol DSESEnvelopeDocument
@end

@interface DSESEnvelopeDocument : DSESObject

/*  [optional]
 */
@property(nonatomic) NSArray<NSString*>* addedRecipientIds;
/*  [optional]
 */
@property(nonatomic) NSString* attachmentTabId;
/* Specifies the Authoritative copy feature. If set to true the Authoritative copy feature is enabled. [optional]
 */
@property(nonatomic) NSString* authoritativeCopy;

@property(nonatomic) DSESPropertyMetadata* authoritativeCopyMetadata;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESSignatureType>* availableDocumentTypes;
/*  [optional]
 */
@property(nonatomic) NSString* containsPdfFormFields;
/*  [optional]
 */
@property(nonatomic) NSString* display;

@property(nonatomic) DSESPropertyMetadata* displayMetadata;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESNameValue>* documentFields;
/* Specifies the document ID number that the tab is placed on. This must refer to an existing Document's ID attribute. [optional]
 */
@property(nonatomic) NSString* documentId;
/*  [optional]
 */
@property(nonatomic) NSString* documentIdGuid;

@property(nonatomic) DSESErrorDetails* errorDetails;
/*  [optional]
 */
@property(nonatomic) NSString* includeInDownload;

@property(nonatomic) DSESPropertyMetadata* includeInDownloadMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* name;

@property(nonatomic) DSESPropertyMetadata* nameMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* order;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESPage>* pages;
/*  [optional]
 */
@property(nonatomic) NSString* signerMustAcknowledge;

@property(nonatomic) DSESPropertyMetadata* signerMustAcknowledgeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* sizeBytes;
/* When set to **true**, the sender cannot change any attributes of the recipient. Used only when working with template recipients.  [optional]
 */
@property(nonatomic) NSString* templateLocked;
/* When set to **true**, the sender may not remove the recipient. Used only when working with template recipients. [optional]
 */
@property(nonatomic) NSString* templateRequired;
/*  [optional]
 */
@property(nonatomic) NSString* type;
/*  [optional]
 */
@property(nonatomic) NSString* uri;

@end
