#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESConnectSalesforceField.h>
@protocol DSESConnectSalesforceField;
@class DSESConnectSalesforceField;



@protocol DSESConnectSalesforceObject
@end

@interface DSESConnectSalesforceObject : DSESObject

/*  [optional]
 */
@property(nonatomic) NSString* active;
/*  [optional]
 */
@property(nonatomic) NSString* _description;
/*  [optional]
 */
@property(nonatomic) NSString* _id;
/*  [optional]
 */
@property(nonatomic) NSString* insert;
/*  [optional]
 */
@property(nonatomic) NSString* onCompleteOnly;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESConnectSalesforceField>* selectFields;
/*  [optional]
 */
@property(nonatomic) NSString* sfObject;
/*  [optional]
 */
@property(nonatomic) NSString* sfObjectName;
/*  [optional]
 */
@property(nonatomic) NSArray<DSESConnectSalesforceField>* updateFields;

@end
