#import <Foundation/Foundation.h>
#import <DSESObject.h>

/**
* DocuSign REST API
* The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.
*
* OpenAPI spec version: v2.1
* Contact: devcenter@docusign.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import <DSESAdminMessage.h>
#import <DSESAskAnAdmin.h>
#import <DSESSettingsMetadata.h>
@protocol DSESAdminMessage;
@class DSESAdminMessage;
@protocol DSESAskAnAdmin;
@class DSESAskAnAdmin;
@protocol DSESSettingsMetadata;
@class DSESSettingsMetadata;



@protocol DSESAccountUISettings
@end

@interface DSESAccountUISettings : DSESObject


@property(nonatomic) DSESAdminMessage* adminMessage;

@property(nonatomic) DSESAskAnAdmin* askAnAdmin;
/*  [optional]
 */
@property(nonatomic) NSString* enableAdminMessage;

@property(nonatomic) DSESSettingsMetadata* enableAdminMessageMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableEasySignCanUseMultiTemplateApply;

@property(nonatomic) DSESSettingsMetadata* enableEasySignCanUseMultiTemplateApplyMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableEasySignTemplateUpload;

@property(nonatomic) DSESSettingsMetadata* enableEasySignTemplateUploadMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* enableEnvelopeCopyWithData;

@property(nonatomic) DSESSettingsMetadata* enableEnvelopeCopyWithDataMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* hideSendAnEnvelope;

@property(nonatomic) DSESSettingsMetadata* hideSendAnEnvelopeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* hideUseATemplate;
/*  [optional]
 */
@property(nonatomic) NSString* hideUseATemplateInPrepare;

@property(nonatomic) DSESSettingsMetadata* hideUseATemplateInPrepareMetadata;

@property(nonatomic) DSESSettingsMetadata* hideUseATemplateMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* orderBasedRecipientIdGeneration;

@property(nonatomic) DSESSettingsMetadata* orderBasedRecipientIdGenerationMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* removeEnvelopeForwarding;

@property(nonatomic) DSESSettingsMetadata* removeEnvelopeForwardingMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* shouldRedactAccessCode;

@property(nonatomic) DSESSettingsMetadata* shouldRedactAccessCodeMetadata;
/*  [optional]
 */
@property(nonatomic) NSString* uploadNewImageToSignOrInitial;

@property(nonatomic) DSESSettingsMetadata* uploadNewImageToSignOrInitialMetadata;

@end
